<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

//2025_05_28_205550_translate_countries_names
class TranslateCountriesNames extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('countries', function (Blueprint $table) {
            $table->string('description_es')->nullable();
        });

        $countries = DB::connection('tenant')->table('countries')->get();
        $countries_data = [
            'AX' => 'ISLAS ÅLAND',
            'AF' => 'AFGANISTÁN',
            'AL' => 'ALBANIA',
            'DZ' => 'ARGELIA',
            'AS' => 'SAMOA AMERICANA',
            'AD' => 'ANDORRA',
            'AO' => 'ANGOLA',
            'AI' => 'ANGUILA',
            'AQ' => 'ANTÁRTIDA',
            'AG' => 'ANTIGUA Y BARBUDA',
            'AR' => 'ARGENTINA',
            'AM' => 'ARMENIA',
            'AW' => 'ARUBA',
            'AU' => 'AUSTRALIA',
            'AT' => 'AUSTRIA',
            'AZ' => 'AZERBAIYÁN',
            'BS' => 'BAHAMAS',
            'BH' => 'BARÉIN',
            'BD' => 'BANGLADÉS',
            'BB' => 'BARBADOS',
            'BY' => 'BIELORRUSIA',
            'BE' => 'BÉLGICA',
            'BZ' => 'BELICE',
            'BJ' => 'BENÍN',
            'BM' => 'BERMUDAS',
            'BT' => 'BUTÁN',
            'BO' => 'BOLIVIA',
            'BA' => 'BOSNIA Y HERZEGOVINA',
            'BW' => 'BOTSUANA',
            'BV' => 'ISLA BOUVET',
            'BR' => 'BRASIL',
            'IO' => 'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO',
            'BN' => 'BRUNÉI',
            'BG' => 'BULGARIA',
            'BF' => 'BURKINA FASO',
            'BI' => 'BURUNDI',
            'KH' => 'CAMBOYA',
            'CM' => 'CAMERÚN',
            'CA' => 'CANADÁ',
            'CV' => 'CABO VERDE',
            'KY' => 'ISLAS CAIMÁN',
            'CF' => 'REPÚBLICA CENTROAFRICANA',
            'TD' => 'CHAD',
            'CL' => 'CHILE',
            'CN' => 'CHINA',
            'CX' => 'ISLA DE NAVIDAD',
            'CC' => 'ISLAS COCOS',
            'CO' => 'COLOMBIA',
            'KM' => 'COMORAS',
            'CD' => 'REPÚBLICA DEMOCRÁTICA DEL CONGO',
            'CG' => 'REPÚBLICA DEL CONGO',
            'CK' => 'ISLAS COOK',
            'CR' => 'COSTA RICA',
            'CI' => 'COSTA DE MARFIL',
            'HR' => 'CROACIA',
            'CU' => 'CUBA',
            'CY' => 'CHIPRE',
            'CZ' => 'REPÚBLICA CHECA',
            'DK' => 'DINAMARCA',
            'DJ' => 'YIBUTI',
            'DM' => 'DOMINICA',
            'DO' => 'REPÚBLICA DOMINICANA',
            'EC' => 'ECUADOR',
            'EG' => 'EGIPTO',
            'SV' => 'EL SALVADOR',
            'GQ' => 'GUINEA ECUATORIAL',
            'ER' => 'ERITREA',
            'EE' => 'ESTONIA',
            'ET' => 'ETIOPÍA',
            'FK' => 'ISLAS MALVINAS',
            'FO' => 'ISLAS FEROE',
            'FJ' => 'FIYI',
            'FI' => 'FINLANDIA',
            'FR' => 'FRANCIA',
            'GF' => 'GUAYANA FRANCESA',
            'PF' => 'POLINESIA FRANCESA',
            'TF' => 'TERRITORIOS AUSTRALES FRANCESES',
            'GA' => 'GABÓN',
            'GM' => 'GAMBIA',
            'GE' => 'GEORGIA',
            'DE' => 'ALEMANIA',
            'GH' => 'GHANA',
            'GI' => 'GIBRALTAR',
            'GR' => 'GRECIA',
            'GL' => 'GROENLANDIA',
            'GD' => 'GRANADA',
            'GP' => 'GUADALUPE',
            'GU' => 'GUAM',
            'GT' => 'GUATEMALA',
            'GN' => 'GUINEA',
            'GW' => 'GUINEA-BISÁU',
            'GY' => 'GUYANA',
            'HT' => 'HAITÍ',
            'HM' => 'ISLAS HEARD Y MCDONALD',
            'HN' => 'HONDURAS',
            'HK' => 'HONG KONG',
            'HU' => 'HUNGRÍA',
            'IS' => 'ISLANDIA',
            'IN' => 'INDIA',
            'ID' => 'INDONESIA',
            'IR' => 'IRÁN',
            'IQ' => 'IRAK',
            'IE' => 'IRLANDA',
            'IL' => 'ISRAEL',
            'IT' => 'ITALIA',
            'JM' => 'JAMAICA',
            'JP' => 'JAPÓN',
            'JO' => 'JORDANIA',
            'KZ' => 'KAZAJISTÁN',
            'KE' => 'KENIA',
            'KI' => 'KIRIBATI',
            'KP' => 'COREA DEL NORTE',
            'KR' => 'COREA DEL SUR',
            'KW' => 'KUWAIT',
            'KG' => 'KIRGUISTÁN',
            'LA' => 'LAOS',
            'LV' => 'LETONIA',
            'LB' => 'LÍBANO',
            'LS' => 'LESOTO',
            'LR' => 'LIBERIA',
            'LY' => 'LIBIA',
            'LI' => 'LIECHTENSTEIN',
            'LT' => 'LITUANIA',
            'LU' => 'LUXEMBURGO',
            'MO' => 'MACAO',
            'MK' => 'MACEDONIA DEL NORTE',
            'MG' => 'MADAGASCAR',
            'MW' => 'MALAUI',
            'MY' => 'MALASIA',
            'MV' => 'MALDIVAS',
            'ML' => 'MALÍ',
            'MT' => 'MALTA',
            'MH' => 'ISLAS MARSHALL',
            'MQ' => 'MARTINICA',
            'MR' => 'MAURITANIA',
            'MU' => 'MAURICIO',
            'YT' => 'MAYOTTE',
            'MX' => 'MÉXICO',
            'FM' => 'MICRONESIA',
            'MD' => 'MOLDAVIA',
            'MC' => 'MÓNACO',
            'MN' => 'MONGOLIA',
            'MS' => 'MONTSERRAT',
            'MA' => 'MARRUECOS',
            'MZ' => 'MOZAMBIQUE',
            'MM' => 'MYANMAR',
            'NA' => 'NAMIBIA',
            'NR' => 'NAURU',
            'NP' => 'NEPAL',
            'NL' => 'PAÍSES BAJOS',
            'AN' => 'ANTILLAS NEERLANDESAS',
            'NC' => 'NUEVA CALEDONIA',
            'NZ' => 'NUEVA ZELANDA',
            'NI' => 'NICARAGUA',
            'NE' => 'NÍGER',
            'NG' => 'NIGERIA',
            'NU' => 'NIUE',
            'NF' => 'ISLA NORFOLK',
            'MP' => 'ISLAS MARIANAS DEL NORTE',
            'NO' => 'NORUEGA',
            'OM' => 'OMÁN',
            'PK' => 'PAKISTÁN',
            'PW' => 'PALAOS',
            'PS' => 'PALESTINA',
            'PA' => 'PANAMÁ',
            'PG' => 'PAPÚA NUEVA GUINEA',
            'PY' => 'PARAGUAY',
            'PE' => 'PERÚ',
            'PH' => 'FILIPINAS',
            'PN' => 'ISLAS PITCAIRN',
            'PL' => 'POLONIA',
            'PT' => 'PORTUGAL',
            'PR' => 'PUERTO RICO',
            'QA' => 'CATAR',
            'RE' => 'REUNIÓN',
            'RO' => 'RUMANIA',
            'RU' => 'RUSIA',
            'RW' => 'RUANDA',
            'SH' => 'SANTA ELENA',
            'KN' => 'SAN CRISTÓBAL Y NIEVES',
            'LC' => 'SANTA LUCÍA',
            'PM' => 'SAN PEDRO Y MIQUELÓN',
            'VC' => 'SAN VICENTE Y LAS GRANADINAS',
            'WS' => 'SAMOA',
            'SM' => 'SAN MARINO',
            'ST' => 'SANTO TOMÉ Y PRÍNCIPE',
            'SA' => 'ARABIA SAUDITA',
            'SN' => 'SENEGAL',
            'CS' => 'SERBIA Y MONTENEGRO',
            'SC' => 'SEYCHELLES',
            'SL' => 'SIERRA LEONA',
            'SG' => 'SINGAPUR',
            'SK' => 'ESLOVAQUIA',
            'SI' => 'ESLOVENIA',
            'SB' => 'ISLAS SALOMÓN',
            'SO' => 'SOMALIA',
            'ZA' => 'SUDÁFRICA',
            'GS' => 'ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR',
            'ES' => 'ESPAÑA',
            'LK' => 'SRI LANKA',
            'SD' => 'SUDÁN',
            'SR' => 'SURINAM',
            'SJ' => 'SVALBARD Y JAN MAYEN',
            'SZ' => 'SUAZILANDIA',
            'SE' => 'SUECIA',
            'CH' => 'SUIZA',
            'SY' => 'SIRIA',
            'TW' => 'TAIWÁN',
            'TJ' => 'TAYIKISTÁN',
            'TZ' => 'TANZANIA',
            'TH' => 'TAILANDIA',
            'TL' => 'TIMOR ORIENTAL',
            'TG' => 'TOGO',
            'TK' => 'TOKELAU',
            'TO' => 'TONGA',
            'TT' => 'TRINIDAD Y TOBAGO',
            'TN' => 'TÚNEZ',
            'TR' => 'TURQUÍA',
            'TM' => 'TURKMENISTÁN',
            'TC' => 'ISLAS TURCAS Y CAICOS',
            'TV' => 'TUVALU',
            'UG' => 'UGANDA',
            'UA' => 'UCRANIA',
            'AE' => 'EMIRATOS ÁRABES UNIDOS',
            'GB' => 'REINO UNIDO',
            'US' => 'ESTADOS UNIDOS',
            'UM' => 'ISLAS ULTRAMARINAS DE ESTADOS UNIDOS',
            'UY' => 'URUGUAY',
            'UZ' => 'UZBEKISTÁN',
            'VU' => 'VANUATU',
            'VA' => 'CIUDAD DEL VATICANO',
            'VE' => 'VENEZUELA',
            'VN' => 'VIETNAM',
            'VG' => 'ISLAS VÍRGENES BRITÁNICAS',
            'VI' => 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS',
            'WF' => 'WALLIS Y FUTUNA',
            'EH' => 'SAHARA OCCIDENTAL',
            'YE' => 'YEMEN',
            'ZM' => 'ZAMBIA',
            'ZW' => 'ZIMBABUE'
        ];

        foreach ($countries as $country) {
            DB::connection('tenant')
                ->table('countries')
                ->where('id', $country->id)
                ->update(['description_es' => $countries_data[$country->id]]);
        }
    }   



    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('countries', function (Blueprint $table) {
            $table->dropColumn('description_es');
        });
    }
}
