<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class InsertLedgerAccountRecognition extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::table('ledger_account_recognitions')->insert([
            [
                'code' => '10',
                'name' => 'EFECTIVO Y EQUIVALENTES DE EFECTIVO',
                'content' => 'Agrupa medios de pago como efectivo, cheques, giros y depósitos en instituciones financieras, además de equivalentes de efectivo disponibles a requerimiento del titular. También abarca saldos sujetos a restricción parcial, clasificados como activo disponible. Recursos inmediatos para pagos.',
                'recognition' => 'Las transacciones se reconocen al valor nominal. Los saldos en moneda extranjera se convierten a moneda local al tipo de cambio aplicable en la fecha de los estados financieros. Los fondos fijos y saldos en caja se ajustan según su naturaleza, reflejando la liquidez inmediata de estos recursos.',
                'comments' => 'Los equivalentes de efectivo pueden encontrarse en otras cuentas, como inversiones financieras de pronta realización. Para el estado de flujos de efectivo, se excluyen los importes con restricción de uso. Los montos asignados a fondos fijos mantienen un saldo autorizado específico.',
            ],
            //11	INVERSIONES FINANCIERAS	Incluye inversiones mantenidas para negociación y disponibles para la venta, así como compromisos de compra futura registrados en la fecha de contratación. Engloba instrumentos financieros primarios y otros con fines de rentabilidad. También abarca valores mobiliarios.	Se registran al costo de adquisición inicialmente. Posteriormente, se miden al valor razonable; si este no puede determinarse de forma confiable, se usa el costo. Las ganancias o pérdidas por medición se reflejan según su naturaleza (negociación o disponibles para la venta) en las cuentas correspondientes.	Si se trata de inversiones en moneda extranjera, se convierten al tipo de cambio al cierre del período. Las variaciones de valor razonable en instrumentos mantenidos para negociación afectan resultados. Para los disponibles para la venta, los cambios se registran en una subcuenta de patrimonio.
            [
                'code' => '11',
                'name' => 'INVERSIONES FINANCIERAS',
                'content' => 'Incluye inversiones mantenidas para negociación y disponibles para la venta, así como compromisos de compra futura registrados en la fecha de contratación. Engloba instrumentos financieros primarios y otros con fines de rentabilidad. También abarca valores mobiliarios.',
                'recognition' => 'Se registran al costo de adquisición inicialmente. Posteriormente, se miden al valor razonable; si este no puede determinarse de forma confiable, se usa el costo. Las ganancias o pérdidas por medición se reflejan según su naturaleza (negociación o disponibles para la venta) en las cuentas correspondientes.',
                'comments' => 'Si se trata de inversiones en moneda extranjera, se convierten al tipo de cambio al cierre del período. Las variaciones de valor razonable en instrumentos mantenidos para negociación afectan resultados. Para los disponibles para la venta, los cambios se registran en una subcuenta de patrimonio.',
            ],
            //12	CUENTAS POR COBRAR COMERCIALES - TERCEROS	Agrupa derechos de cobro a terceros por la venta de bienes o servicios del giro empresarial. Incluye facturas, letras y otros documentos que evidencian una relación comercial. Permite identificar saldos pendientes por operaciones de carácter principal.	Se reconocen inicialmente al valor razonable, habitualmente igual al costo. Luego se miden al costo amortizado, salvo indicios de deterioro que exijan una provisión. Las cuentas en moneda extranjera se traducen al tipo de cambio aplicable a la fecha de los estados financieros.	Los saldos acreedores se presentan como pasivo. La subcuenta 191 acumula la estimación de cobranza dudosa. Al confirmarse la incobrabilidad, se elimina tanto el derecho de cobro como la valuación. Incluye notas de débito o crédito por devoluciones y ajustes comerciales.
            [
                'code' => '12',
                'name' => 'CUENTAS POR COBRAR COMERCIALES - TERCEROS',
                'content' => 'Agrupa derechos de cobro a terceros por la venta de bienes o servicios del giro empresarial. Incluye facturas, letras y otros documentos que evidencian una relación comercial. Permite identificar saldos pendientes por operaciones de carácter principal.',
                'recognition' => 'Se reconocen inicialmente al valor razonable, habitualmente igual al costo. Luego se miden al costo amortizado, salvo indicios de deterioro que exijan una provisión. Las cuentas en moneda extranjera se traducen al tipo de cambio aplicable a la fecha de los estados financieros.',
                'comments' => 'Los saldos acreedores se presentan como pasivo. La subcuenta 191 acumula la estimación de cobranza dudosa. Al confirmarse la incobrabilidad, se elimina tanto el derecho de cobro como la valuación. Incluye notas de débito o crédito por devoluciones y ajustes comerciales.',
            ],
            //13	CUENTAS POR COBRAR COMERCIALES - RELACIONADAS	Agrupa derechos de cobro a entidades vinculadas resultantes de ventas de bienes o servicios en la actividad económica principal. Incluye facturas, letras y otros documentos comerciales. Permite diferenciar los saldos con partes relacionadas de los mantenidos con terceros.	Se reconocen al valor razonable en su inicio y luego se miden al costo amortizado, salvo deterioros que exijan provisión. Las cuentas en moneda extranjera se convierten al tipo de cambio de la fecha de los estados financieros. Las pérdidas por deterioro se reflejan con una cuenta de valuación.	Si el saldo resulta acreedor, se clasifica como pasivo. La subcuenta 192 acumula la estimación de cobranza dudosa. Al confirmarse la incobrabilidad, se da de baja el activo y la provisión. Incluye descuentos, devoluciones y bonificaciones posteriores a la venta.
            [
                'code' => '13',
                'name' => 'CUENTAS POR COBRAR COMERCIALES - RELACIONADAS',
                'content' => 'Agrupa derechos de cobro a entidades vinculadas resultantes de ventas de bienes o servicios en la actividad económica principal. Incluye facturas, letras y otros documentos comerciales. Permite diferenciar los saldos con partes relacionadas de los mantenidos con terceros.',
                'recognition' => 'Se reconocen al valor razonable en su inicio y luego se miden al costo amortizado, salvo deterioros que exijan provisión. Las cuentas en moneda extranjera se convierten al tipo de cambio de la fecha de los estados financieros. Las pérdidas por deterioro se reflejan con una cuenta de valuación.',
                'comments' => 'Si el saldo resulta acreedor, se clasifica como pasivo. La subcuenta 192 acumula la estimación de cobranza dudosa. Al confirmarse la incobrabilidad, se da de baja el activo y la provisión. Incluye descuentos, devoluciones y bonificaciones posteriores a la venta.',
            ],
            // 14	CTAS POR COBRAR AL PERSONAL, ACCIONISTAS, SOC. Y DIR.	Agrupa los importes adeudados por personal, accionistas, socios, directores y gerentes, ajenos a la actividad comercial. Incluye préstamos, anticipos y aportes pendientes de capital. No forman parte de los créditos comerciales usuales de la empresa.	Se registran al valor razonable al inicio, luego se miden al costo amortizado. Cuando existe evidencia de incobrabilidad, se constituye una cuenta de valuación que reduce el saldo. Para cuentas en moneda extranjera, se aplica el tipo de cambio de la fecha de presentación de los estados financieros.	Las suscripciones de capital por cobrar se muestran deduciendo la cuenta de patrimonio respectiva. La subcuenta 193 concentra la estimación de cobranza dudosa. Cuando se comprueba el carácter incobrable, se dan de baja la cuenta original y la respectiva provisión en forma simultánea.
            [
                'code' => '14',
                'name' => 'CTAS POR COBRAR AL PERSONAL, ACCIONISTAS, SOC. Y DIR.',
                'content' => 'Agrupa los importes adeudados por personal, accionistas, socios, directores y gerentes, ajenos a la actividad comercial. Incluye préstamos, anticipos y aportes pendientes de capital. No forman parte de los créditos comerciales usuales de la empresa.',
                'recognition' => 'Se registran al valor razonable al inicio, luego se miden al costo amortizado. Cuando existe evidencia de incobrabilidad, se constituye una cuenta de valuación que reduce el saldo. Para cuentas en moneda extranjera, se aplica el tipo de cambio de la fecha de presentación de los estados financieros.',
                'comments' => 'Las suscripciones de capital por cobrar se muestran deduciendo la cuenta de patrimonio respectiva. La subcuenta 193 concentra la estimación de cobranza dudosa. Cuando se comprueba el carácter incobrable, se dan de baja la cuenta original y la respectiva provisión en forma simultánea.',
            ],
            // 16	CUENTAS POR COBRAR DIVERSAS - TERCEROS	Agrupa derechos de cobro a terceros por transacciones distintas del objeto principal, tales como préstamos ocasionales, regalías, dividendos y operaciones no habituales. Involucra documentos o convenios que no provienen directamente de la venta de bienes o servicios regulares.	Se registran inicialmente al valor razonable, luego se miden al costo amortizado, excepto activos financieros que se miden al valor razonable si es determinable. De existir deterioro en las cuentas a costo amortizado, se registra una provisión. Las partidas en moneda extranjera se traducen al tipo de cambio al cierre.	La subcuenta 194 agrupa la estimación de cobranza dudosa. Los intereses, regalías y dividendos se reconocen según el transcurso del tiempo, las condiciones contractuales o la fecha de derecho. Al confirmar la incobrabilidad, se elimina la cuenta y la provisión. Incluye operaciones ocasionales con terceros.
            [
                'code' => '16',
                'name' => 'CUENTAS POR COBRAR DIVERSAS - TERCEROS',
                'content' => 'Agrupa derechos de cobro a terceros por transacciones distintas del objeto principal, tales como préstamos ocasionales, regalías, dividendos y operaciones no habituales. Involucra documentos o convenios que no provienen directamente de la venta de bienes o servicios regulares.',
                'recognition' => 'Se registran inicialmente al valor razonable, luego se miden al costo amortizado, excepto activos financieros que se miden al valor razonable si es determinable. De existir deterioro en las cuentas a costo amortizado, se registra una provisión. Las partidas en moneda extranjera se traducen al tipo de cambio al cierre.',
                'comments' => 'La subcuenta 194 agrupa la estimación de cobranza dudosa. Los intereses, regalías y dividendos se reconocen según el transcurso del tiempo, las condiciones contractuales o la fecha de derecho. Al confirmar la incobrabilidad, se elimina la cuenta y la provisión. Incluye operaciones ocasionales con terceros.',
            ],
            // 17	CUENTAS POR COBRAR DIVERSAS - RELACIONADAS	Agrupa derechos de cobro a entidades relacionadas por transacciones distintas de las ventas propias. Puede incluir regalías, dividendos, préstamos especiales o acuerdos no propios de la actividad principal. Separa estos saldos de los generados con terceros para mayor claridad.	Se miden inicialmente al valor razonable. Posteriormente se aplican las reglas de costo amortizado o valor razonable, según corresponda. La provisión por deterioro reduce la cuenta cuando se estime incobrable. Si las operaciones son en moneda extranjera, se reexpresan al tipo de cambio al cierre del período.	La subcuenta 195 concentra la estimación de cobranza dudosa. Los intereses, regalías y dividendos se reconocen conforme a las cláusulas pactadas o al devengo correspondiente. Al evidenciar incobrabilidad, se da de baja el activo junto con su provisión. Contribuye a separar operaciones con partes vinculadas.
            [
                'code' => '17',
                'name' => 'CUENTAS POR COBRAR DIVERSAS - RELACIONADAS',
                'content' => 'Agrupa derechos de cobro a entidades relacionadas por transacciones distintas de las ventas propias. Puede incluir regalías, dividendos, préstamos especiales o acuerdos no propios de la actividad principal. Separa estos saldos de los generados con terceros para mayor claridad.',
                'recognition' => 'Se miden inicialmente al valor razonable. Posteriormente se aplican las reglas de costo amortizado o valor razonable, según corresponda. La provisión por deterioro reduce la cuenta cuando se estime incobrable. Si las operaciones son en moneda extranjera, se reexpresan al tipo de cambio al cierre del período.',
                'comments' => 'La subcuenta 195 concentra la estimación de cobranza dudosa. Los intereses, regalías y dividendos se reconocen conforme a las cláusulas pactadas o al devengo correspondiente. Al evidenciar incobrabilidad, se da de baja el activo junto con su provisión. Contribuye a separar operaciones con partes vinculadas.',
            ],
            // 18	SERVICIOS Y OTROS CONTRATADOS POR ANTICIPADO	Agrupa servicios contratados para uso futuro o cuya utilidad se extiende más allá del período corriente, así como primas pagadas por opciones financieras. Representa costos o gastos pagados por anticipado que brindarán beneficios en períodos posteriores.	Se mide al costo, menos el consumo periódico de los beneficios económicos. Las primas por opciones se reconocen al valor razonable, con cambios en resultados. A medida que se utiliza el servicio o expira la vigencia, se transfiere el importe a los gastos del período. Ajuste por moneda extranjera según tipo de cambio al cierre.	La subcuenta 184 agrupa las primas pagadas por opciones. Sus variaciones se contabilizan según resulten favorables o desfavorables. La subcuenta 185 para mantenimiento de activos se revierte al devengar el gasto. Permite controlar partidas prepagadas y su reflejo progresivo en la contabilidad.
            [
                'code' => '18',
                'name' => 'SERVICIOS Y OTROS CONTRATADOS POR ANTICIPADO',
                'content' => 'Agrupa servicios contratados para uso futuro o cuya utilidad se extiende más allá del período corriente, así como primas pagadas por opciones financieras. Representa costos o gastos pagados por anticipado que brindarán beneficios en períodos posteriores.',
                'recognition' => 'Se mide al costo, menos el consumo periódico de los beneficios económicos. Las primas por opciones se reconocen al valor razonable, con cambios en resultados. A medida que se utiliza el servicio o expira la vigencia, se transfiere el importe a los gastos del período. Ajuste por moneda extranjera según tipo de cambio al cierre.',
                'comments' => 'La subcuenta 184 agrupa las primas pagadas por opciones. Sus variaciones se contabilizan según resulten favorables o desfavorables. La subcuenta 185 para mantenimiento de activos se revierte al devengar el gasto. Permite controlar partidas prepagadas y su reflejo progresivo en la contabilidad.',
            ],
            // 19	ESTIMACION DE CUENTAS DE COBRANZA DUDOSA	Agrupa las provisiones para incobrabilidad asociadas a las cuentas por cobrar comerciales, diversas y relacionadas. Reconoce el posible deterioro en la recuperabilidad de los créditos. Permite una presentación fiel de los activos en el balance, separando el valor nominal de la estimación de pérdidas.	Se registra cuando hay evidencia de difícil cobro, afectando simultáneamente la cuenta de gasto o pérdida. Las cuentas en moneda extranjera se ajustan al tipo de cambio al cierre. Si la incobrabilidad se concreta, se elimina la cuenta de activo y la provisión. Puede revertirse si mejora la expectativa de cobro.	Esta estimación se presenta como cuenta de valuación que disminuye las cuentas por cobrar. Aplica a cuentas de la clase 1, 2, 3 y otras que acumulen derechos de cobro. Facilita el reconocimiento oportuno de pérdidas potenciales. Al confirmarse la incobrabilidad, se realiza el castigo contable.
            [
                'code' => '19',
                'name' => 'ESTIMACION DE CUENTAS DE COBRANZA DUDOSA',
                'content' => 'Agrupa las provisiones para incobrabilidad asociadas a las cuentas por cobrar comerciales, diversas y relacionadas. Reconoce el posible deterioro en la recuperabilidad de los créditos. Permite una presentación fiel de los activos en el balance, separando el valor nominal de la estimación de pérdidas.',
                'recognition' => 'Se registra cuando hay evidencia de difícil cobro, afectando simultáneamente la cuenta de gasto o pérdida. Las cuentas en moneda extranjera se ajustan al tipo de cambio al cierre. Si la incobrabilidad se concreta, se elimina la cuenta de activo y la provisión. Puede revertirse si mejora la expectativa de cobro.',
                'comments' => 'Esta estimación se presenta como cuenta de valuación que disminuye las cuentas por cobrar. Aplica a cuentas de la clase 1, 2, 3 y otras que acumulen derechos de cobro. Facilita el reconocimiento oportuno de pérdidas potenciales. Al confirmarse la incobrabilidad, se realiza el castigo contable.',
            ],
            // 20	MERCADERIAS	Agrupa los bienes adquiridos para su venta directa, sin transformación, cumpliendo el rol de mercaderías. Se incluyen artículos terminados o a ser comercializados tal como fueron comprados. Representa el inventario destinado a las actividades de comercialización de la empresa.	Se reconoce al costo de adquisición, que incluye gastos necesarios para ubicarlos en su condición actual. Al venderse, se reduce la cuenta aplicando métodos como PEPS, promedio o identificación específica. Al cierre, se valora al menor entre costo y valor neto de realización. Ajustes monetarios se llevan a resultados.	Las mercaderías en consignación se presentan en cuentas de orden si pertenecen a terceros. Los castigos implican dar de baja la cuenta y, si existe, la estimación por desvalorización (subcuenta 291). No se incluyen bienes recibidos para exhibición o depósito de terceros. Simplifica el control de inventarios comerciales.
            [
                'code' => '20',
                'name' => 'MERCADERIAS',
                'content' => 'Agrupa los bienes adquiridos para su venta directa, sin transformación, cumpliendo el rol de mercaderías. Se incluyen artículos terminados o a ser comercializados tal como fueron comprados.',
                'recognition' => 'Se reconoce al costo de adquisición, que incluye gastos necesarios para ubicarlos en su condición actual. Al venderse, se reduce la cuenta aplicando métodos como PEPS, promedio o identificación específica. Al cierre, se valora al menor entre costo y valor neto de realización. Ajustes monetarios se llevan a resultados.',
                'comments' => 'Las mercaderías en consignación se presentan en cuentas de orden si pertenecen a terceros. Los castigos implican dar de baja la cuenta y, si existe, la estimación por desvalorización (subcuenta 291). No se incluyen bienes recibidos para exhibición o depósito de terceros. Simplifica el control de inventarios comerciales.',
            ],
            // 21	PRODUCTOS TERMINADOS	Agrupa bienes fabricados o producidos por la empresa, destinados a la venta. Incluye costos de servicios con ingresos por reconocer y costos de financiación capitalizados. Refleja productos terminados listos para su comercialización, así como servicios concluidos pendientes de facturación.	Se reconocen al costo de fabricación o producción, que incluye todos los costos necesarios para su condición y ubicación. Se aplican fórmulas de costeo como PEPS, promedio o costo identificado. Cuando hay productos conjuntos, se distribuye el costo total en forma uniforme. Los costos financieros van a la subcuenta 218.	Las mermas con valor de recuperación van a la cuenta 22. Los servicios terminados reconocen costo e ingreso simultáneamente. Al desvalorizar, primero se reduce el componente financiero activado. El castigo se registra junto con la subcuenta 292 de desvalorización.
            [
                'code' => '21',
                'name' => 'PRODUCTOS TERMINADOS',
                'content' => 'Agrupa bienes fabricados o producidos por la empresa, destinados a la venta. Incluye costos de servicios con ingresos por reconocer y costos de financiación capitalizados. Refleja productos terminados listos para su comercialización, así como servicios concluidos pendientes de facturación.',
                'recognition' => 'Se reconocen al costo de fabricación o producción, que incluye todos los costos necesarios para su condición y ubicación. Se aplican fórmulas de costeo como PEPS, promedio o costo identificado. Cuando hay productos conjuntos, se distribuye el costo total en forma uniforme. Los costos financieros van a la subcuenta 218.',
                'comments' => 'Las mermas con valor de recuperación van a la cuenta 22. Los servicios terminados reconocen costo e ingreso simultáneamente. Al desvalorizar, primero se reduce el componente financiero activado. El castigo se registra junto con la subcuenta 292 de desvalorización.',
            ],
            // 22	SUBPRODUCTOS, DESECHOS Y DESPERDICIOS	Agrupa productos accesorios (subproductos) y residuos (desechos, desperdicios) que resultan de la producción principal, pero conservan algún valor de realización. Permite separar los ingresos de su venta y los costos del proceso que los generó, reflejando su contribución secundaria.	Se registran al costo y se comparan con el valor neto de realización, usando una cuenta de valuación cuando haya diferencia. Si es impracticable determinar el costo, se valoran al valor neto de realización. Las salidas se miden con métodos de costeo como PEPS o promedio ponderado.	El importe asignado a subproductos, desechos y desperdicios reduce los costos del proceso donde surgieron. Dichos costos pueden acumularse en cuentas de costos (elemento 9). Este tratamiento ayuda a reflejar adecuadamente los resultados y la valuación de la producción.
            [
                'code' => '22',
                'name' => 'SUBPRODUCTOS, DESECHOS Y DESPERDICIOS',
                'content' => 'Agrupa productos accesorios (subproductos) y residuos (desechos, desperdicios) que resultan de la producción principal, pero conservan algún valor de realización. Permite separar los ingresos de su venta y los costos del proceso que los generó, reflejando su contribución secundaria.',
                'recognition' => 'Se registran al costo y se comparan con el valor neto de realización, usando una cuenta de valuación cuando haya diferencia. Si es impracticable determinar el costo, se valoran al valor neto de realización. Las salidas se miden con métodos de costeo como PEPS o promedio ponderado.',
                'comments' => 'El importe asignado a subproductos, desechos y desperdicios reduce los costos del proceso donde surgieron. Dichos costos pueden acumularse en cuentas de costos (elemento 9). Este tratamiento ayuda a reflejar adecuadamente los resultados y la valuación de la producción.',
            ],
            // 23	PRODUCTOS EN PROCESO	Agrupa bienes que están en plena fase de producción al cierre, incluyendo costos directos e indirectos atribuibles. Aplica a procesos industriales, agropecuarios, piscícolas y de servicios. Muestra los recursos invertidos antes de culminar el producto o servicio.	Se agregan costos de mano de obra, materiales directos y costos indirectos. Para agropecuarios o piscícolas, puede usarse el valor razonable si es determinable; de no serlo, el costo. Los costos financieros de existencias calificadas se llevan a la subcuenta 238.	Incluye productos extraídos y servicios en proceso, reflejando costos incurridos no devengados como ingresos. Al desvalorizar, se reduce primero el componente financiero activado. Tras la culminación, se trasladan a productos terminados o se reconocen en el costo de ventas de servicios.}
            [
                'code' => '23',
                'name' => 'PRODUCTOS EN PROCESO',
                'content' => 'Agrupa bienes que están en plena fase de producción al cierre, incluyendo costos directos e indirectos atribuibles. Aplica a procesos industriales, agropecuarios, piscícolas y de servicios. Muestra los recursos invertidos antes de culminar el producto o servicio.',
                'recognition' => 'Se agregan costos de mano de obra, materiales directos y costos indirectos. Para agropecuarios o piscícolas, puede usarse el valor razonable si es determinable; de no serlo, el costo. Los costos financieros de existencias calificadas se llevan a la subcuenta 238. Incluye productos extraídos y servicios en proceso, reflejando costos incurridos no devengados como ingresos. Al desvalorizar, se reduce primero el componente financiero activado. Tras la culminación, se trasladan a productos terminados o se reconocen en el costo de ventas de servicios.',
                'comments' => 'Al desvalorizar, se reduce primero el componente financiero activado. Tras la culminación, se trasladan a productos terminados o se reconocen en el costo de ventas de servicios.',
            ],
            // 24	MATERIAS PRIMAS	Agrupa insumos directamente involucrados en la fabricación de productos terminados. Se incorporan en el producto final y reflejan el costo de adquisición, restando los descuentos comerciales. Es la base material del proceso de transformación.	Se valoran al menor entre costo y valor neto de realización. Si la baja de precio indica que el producto terminado excederá su valor neto realizable, se adopta el costo de reposición. Su salida aplica métodos como PEPS, promedio ponderado o costo identificado.	La subcuenta 295 registra la desvalorización de materias primas. Si se deduce el valor, se examina si la pérdida afecta el producto final. El reconocimiento y control adecuado de su costo permiten asegurar la correcta determinación del resultado y la valuación de los inventarios.
            [
                'code' => '24',
                'name' => 'MATERIAS PRIMAS',
                'content' => 'Agrupa insumos directamente involucrados en la fabricación de productos terminados. Se incorporan en el producto final y reflejan el costo de adquisición, restando los descuentos comerciales. Es la base material del proceso de transformación.',
                'recognition' => 'Se valoran al menor entre costo y valor neto de realización. Si la baja de precio indica que el producto terminado excederá su valor neto realizable, se adopta el costo de reposición. Su salida aplica métodos como PEPS, promedio ponderado o costo identificado.',
                'comments' => 'La subcuenta 295 registra la desvalorización de materias primas. Si se deduce el valor, se examina si la pérdida afecta el producto final. El reconocimiento y control adecuado de su costo permiten asegurar la correcta determinación del resultado y la valuación de los inventarios.',
            ],
            // 25	MATERIALES AUXILIARES, SUMINISTOS Y REPUESTOS	Incluye materiales, suministros y repuestos que participan en la producción, pero no son materia prima principal. Abarca artículos para mantenimiento o reparación que no califican como activos inmovilizados y pueden usarse de manera recurrente en los procesos productivos.	Se miden al costo, considerando gastos necesarios para su condición actual. Al cierre, se emplea el menor entre costo y valor neto de realización. Ante caídas de precio que afecten el producto final, se adopta el costo de reposición. Las salidas siguen métodos como PEPS o promedio.	Si un repuesto sustituido es de vida prolongada y forma parte de un activo, se transfiere a la subcuenta 337. El resto permanece aquí. Las eventuales desvalorizaciones se contabilizan en conjunto con la subcuenta 296, si procede. Permite identificar y controlar insumos secundarios.
            [
                'code' => '25',
                'name' => 'MATERIALES AUXILIARES, SUMINISTOS Y REPUESTOS',
                'content' => 'Incluye materiales, suministros y repuestos que participan en la producción, pero no son materia prima principal. Abarca artículos para mantenimiento o reparación que no califican como activos inmovilizados y pueden usarse de manera recurrente en los procesos productivos.',
                'recognition' => 'Se miden al costo, considerando gastos necesarios para su condición actual. Al cierre, se emplea el menor entre costo y valor neto de realización. Ante caídas de precio que afecten el producto final, se adopta el costo de reposición. Las salidas siguen métodos como PEPS o promedio.',
                'comments' => 'Si un repuesto sustituido es de vida prolongada y forma parte de un activo, se transfiere a la subcuenta 337. El resto permanece aquí. Las eventuales desvalorizaciones se contabilizan en conjunto con la subcuenta 296, si procede. Permite identificar y controlar insumos secundarios.',
            ],
            // 26	ENVASES Y EMBALAJES	Agrupa bienes que sirven de presentación o protección del producto para su venta. Son complementarios, pero importantes en la cadena comercial. Pueden ser descartables o reutilizables y deben distinguirse de otros activos.	Se registran al costo de adquisición. Al cierre, se valora al menor entre costo y valor neto de realización. Si se reducen los precios de venta, puede tomarse el costo de reposición como referencia. Las salidas se reconocen con fórmulas de costeo como PEPS, promedio o costo identificado.	El castigo por desvalorización se registra junto con la subcuenta 297. Aquellos envases y embalajes reutilizables pueden requerir un control aparte para identificar su vida útil. Este rubro permite una óptima contabilidad de los costos de presentación y comercialización.
            [
                'code' => '26',
                'name' => 'ENVASES Y EMBALAJES',
                'content' => 'Agrupa bienes que sirven de presentación o protección del producto para su venta. Son complementarios, pero importantes en la cadena comercial. Pueden ser descartables o reutilizables y deben distinguirse de otros activos.',
                'recognition' => 'Se registran al costo de adquisición. Al cierre, se valora al menor entre costo y valor neto de realización. Si se reducen los precios de venta, puede tomarse el costo de reposición como referencia. Las salidas se reconocen con fórmulas de costeo como PEPS, promedio o costo identificado.',
                'comments' => 'El castigo por desvalorización se registra junto con la subcuenta 297. Aquellos envases y embalajes reutilizables pueden requerir un control aparte para identificar su vida útil. Este rubro permite una óptima contabilidad de los costos de presentación y comercialización.',
            ],
            // 27	ACTIVOS NO CORRIENTES MANTENIDOS PARA LA VENTA	Reúne activos inmovilizados cuya recuperación se prevé por venta, no por uso continuo. Deben estar disponibles para venta inmediata, con alta probabilidad de concretarla. No requieren modificaciones sustanciales antes de ser vendidos.	Se miden al menor entre su importe en libros y valor razonable menos costos de venta. Mientras estén clasificados para la venta, no se deprecian ni amortizan. Si proceden de una combinación de negocios, se valoran a su valor razonable menos costos de venta.	Si dejan de cumplirse los requisitos 
            [
                'code' => '27',
                'name' => 'ACTIVOS NO CORRIENTES MANTENIDOS PARA LA VENTA',
                'content' => 'Reúne activos inmovilizados cuya recuperación se prevé por venta, no por uso continuo. Deben estar disponibles para venta inmediata, con alta probabilidad de concretarla. No requieren modificaciones sustanciales antes de ser vendidos.',
                'recognition' => 'Se miden al menor entre su importe en libros y valor razonable menos costos de venta. Mientras estén clasificados para la venta, no se deprecian ni amortizan. Si proceden de una combinación de negocios, se valoran a su valor razonable menos costos de venta.',
                'comments' => 'Si dejan de cumplirse los requisitos, se reclasifican a la cuenta adecuada. Ante deterioro, primero se afecta el costo financiero capitalizado. Los activos bajo arrendamiento financiero se registran aquí, coordinando con la cuenta 32 para su distinción. Permite evidenciar pasivos por arrendamiento y refleja los derechos de uso durante la vigencia del acuerdo financiero.',
            ],

            // 29	DESVALORIZACION DE INVENTARIOS	Reúne provisiones que cubren el deterioro de inventarios por obsolescencia, daños o caída de precios. Disminuye el valor contable de las existencias para reflejar el menor importe recuperable. Permite exponer fielmente la situación real del inventario.	Se registra cuando el valor neto de realización es inferior al costo, atendiendo obsolescencia, daños o baja de mercado. Reduce la cuenta de inventarios a través de una provisión. Puede revertirse si las condiciones cambian y aumenta el valor recuperable, sin exceder el costo original.	Ayuda a mostrar la correcta valoración de las existencias. Aplica a materias primas, productos en proceso, terminados y afines. Ante pérdida definitiva, se mantiene la provisión o se ajusta a la baja. Al mejorar las circunstancias, se corrige el importe, sin exceder el costo inicial.
            [
                'code' => '29',
                'name' => 'DESVALORIZACION DE INVENTARIOS',
                'content' => 'Reúne provisiones que cubren el deterioro de inventarios por obsolescencia, daños o caída de precios. Disminuye el valor contable de las existencias para reflejar el menor importe recuperable. Permite exponer fielmente la situación real del inventario.',
                'recognition' => 'Se registra cuando el valor neto de realización es inferior al costo, atendiendo obsolescencia, daños o baja de mercado. Reduce la cuenta de inventarios a través de una provisión. Puede revertirse si las condiciones cambian y aumenta el valor recuperable, sin exceder el costo original.',
                'comments' => 'Ayuda a mostrar la correcta valoración de las existencias. Aplica a materias primas, productos en proceso, terminados y afines. Ante pérdida definitiva, se mantiene la provisión o se ajusta a la baja. Al mejorar las circunstancias, se corrige el importe, sin exceder el costo inicial.',
            ],

            ['code' => '30', 'name' => 'INVERSIONES MOBILIARIAS', 'content' => 'Incluye activos financieros con vencimiento fijo o cuantía de cobro determinable, que la empresa pretende y puede mantener hasta su vencimiento. No incluye valores negociables o disponibles para la venta ni préstamos o cuentas por cobrar. Abarca también inversiones en acciones de otras entidades.', 'recognition' => 'Se reconocen al valor razonable más costos de transacción y luego se miden al costo amortizado con tasa de interés efectiva. Si se trata de subsidiarias o asociadas, se usa el método de participación patrimonial. Al evidenciar deterioro, se reduce el valor en libros mediante una provisión.', 'comments' => 'Los instrumentos en moneda extranjera se convierten al tipo de cambio al cierre. Para inversiones accionarias no consolidadas, se aplica el costo o participación patrimonial. Reconoce plusvalías mercantiles al adquirir la inversión y las registra si cumplen con los criterios de combinación de negocios.'],
            ['code' => '31', 'name' => 'PROPIEDADES DE INVERSION', 'content' => 'Abarca terrenos o edificaciones mantenidos para generar rentas o incrementar valor de capital, no usados en producción o fines administrativos ni destinados a venta inmediata. Pueden ser poseídos o tomados en arrendamiento financiero, excluyéndose aquellos cuyo valor razonable no pueda medirse.', 'recognition' => 'Se inician al costo de adquisición; luego se miden al valor razonable o al costo menos depreciación y deterioro si no puede estimarse con fiabilidad el valor de mercado. Los costos financieros se capitalizan hasta la puesta en servicio. Si solo parte genera rentas, se separa en otra cuenta.', 'comments' => 'Si pasa a uso propio o a venta, se reclasifica a la cuenta adecuada. Cuando no exista mercado activo, se puede optar por tasación independiente. Ante desvalorización, primero se reduce el componente financiero capitalizado. Para inversiones en construcción, véase la NIC 40 y la cuenta 32.'],
            ['code' => '32', 'name' => 'ACTIVOS POR DERECHO DE USO', 'content' => 'Incluye bienes adquiridos bajo arrendamiento financiero, registrados por el menor entre su valor razonable y el valor presente de los pagos mínimos. Pueden ser inmuebles, maquinaria o equipo, midiéndose según las políticas aplicables al activo subyacente.', 'recognition' => 'Al reconocimiento inicial, se asimila a un activo adquirido, depreciándose según vida útil. Si el contrato no transfiere la propiedad, la depreciación se limita a la vigencia del convenio. Los intereses se llevan a resultados como costos financieros en cada periodo.', 'comments' => 'Se diferencia de un activo propio por el financiamiento implícito. Se revisan saldos y porción adeudada al cierre. Pueden reclasificarse si termina el contrato o cambia el uso. Permite evidenciar pasivos por arrendamiento y refleja los derechos de uso durante la vigencia del acuerdo financiero.'],
            ['code' => '33', 'name' => 'PROPIEDADES, PLANTA Y EQUIPO', 'content' => 'Reúne bienes tangibles usados para producción, suministro de bienes o servicios, arrendarlos a terceros, o fines administrativos, con una vida útil mayor a un periodo. Incluye terrenos, construcciones, maquinaria, costos de instalación y desmantelamiento, entre otros elementos físicos.', 'recognition' => 'Se miden inicialmente al costo (adquisición, construcción o tasación) más gastos necesarios para su puesta en uso. Luego se conservan al costo menos depreciación y deterioro, o se revalúan. La depreciación inicia cuando están en condiciones de operar, y los intereses se capitalizan hasta ese punto.', 'comments' => 'Mantenimientos rutinarios van a gasto; mejoras se capitalizan. Si se decide vender el bien, se reclasifica a la cuenta 27. Ante deterioro, primero se afecta el costo financiero capitalizado. Los activos bajo arrendamiento financiero se registran aquí, coordinando con la cuenta 32 para su distinción.'],
            ['code' => '34', 'name' => 'INTANGIBLES', 'content' => 'Incluye activos no monetarios, identificables y sin sustancia física (patentes, licencias, software, etc.). Excluye desembolsos en investigación que no cumplan condiciones de capitalización. Refleja derechos o beneficios futuros esperados, con base legal o contractual.', 'recognition' => 'Se valoran inicialmente al costo de adquisición o producción, restando amortización y deterioro. De aplicarse revaluación, se usa el valor revaluado menos amortización y deterioro. La investigación no se capitaliza; la fase de desarrollo se capitaliza si cumple los requisitos específicos.', 'comments' => 'Los costos activados deben generar beneficios económicos futuros probables y medirse con fiabilidad. Pueden tener vida útil definida o indefinida. En exploración minera, se siguen criterios de la NIIF 6 si se adopta. Ajustes por deterioro se registran cuando el valor en libros excede su importe recuperable.'],
            ['code' => '35', 'name' => 'ACTIVOS BIOLOGICOS', 'content' => 'Reúne animales vivos y plantas pertenecientes a actividades agrícolas, pecuarias o piscícolas. Se incluyen crías, cultivos y toda forma de crecimiento biológico gestionado para venta, productos agrícolas o transformación en otros activos biológicos. Muestran la variación natural y desarrollo.', 'recognition' => 'Se valoran al valor razonable menos costos de venta, tanto al reconocimiento inicial como al cierre del periodo. Si no es factible medirlo, se aplica temporalmente el costo menos depreciación y deterioro. Las variaciones en valor se llevan a resultados conforme se generen.', 'comments' => 'Las ganancias o pérdidas por cambios en valor se reflejan en resultados del periodo. Si se esperan vender en lugar de usarse continuamente, se reclasifican a la cuenta 27. Al obtener productos agrícolas, se mueven a existencias. Mantiene la distinción entre fase de crecimiento biológico y productos finales.'],
            ['code' => '36', 'name' => 'DESVALORIZACION DE ACTIVO INMOVILIZADO', 'content' => 'Registra deterioros de inversiones inmobiliarias, propiedades, planta y equipo, intangibles y activos biológicos. Reconoce la caída en su valor recuperable, cuando éste es menor que el valor en libros, derivando una pérdida a fin de exponer el activo a su importe recuperable.', 'recognition' => 'Si el activo se lleva al costo, la pérdida se reconoce en resultados; si estaba revaluado, se reduce la reserva hasta agotarla, y el excedente va a resultados. La reversión es posible si cesan las condiciones que la motivaron, sin exceder el valor que habría tenido sin el deterioro.', 'comments' => 'El deterioro afecta primero el costo financiero capitalizado. Se revisa si existen indicadores (pérdida operativa, cambios de mercado, etc.) para proceder. Inversiones mobiliarias pueden seguir otras reglas. Al revertir, no se supera el valor de costo neto de las depreciaciones regulares.'],
            ['code' => '37', 'name' => 'ACTIVO DIFERIDO', 'content' => 'Incluye activos por diferencias temporarias deducibles (impuesto a la renta y participaciones diferidas), pérdidas tributarias compensables y también intereses no devengados en cuentas por pagar que se separan para mostrar el pasivo a valor de contado. Refleja saldos con beneficio futuro.', 'recognition' => 'Se reconoce cuando es probable la existencia de ganancias fiscales para aplicar las deducciones. Se mide sin descuento financiero, ajustándose de modo recurrente. Los intereses no devengados se compensan contra la cuenta de pasivo, reflejando el importe efectivo de la deuda.', 'comments' => 'Subcuentas 872 y 882 recogen participaciones e impuesto a la renta diferidos. Su recuperación depende de rentas imponibles. Los intereses diferidos surgen de ventas o compras con pago diferido. Se revalúa periódicamente el derecho a compensar pérdidas, según la expectativa de beneficios futuros.'],
            ['code' => '38', 'name' => 'OTROS ACTIVOS', 'content' => 'Agrupa el costo de bienes no empleados en operaciones principales ni destinados a la venta. Incluye obras de arte, colecciones especiales o adquisiciones con fines ajenos a la actividad normal, registrándose en activos a largo plazo y pudiendo requerir un análisis posterior de deterioro.', 'recognition' => 'Se valora al costo, o al valor razonable en casos de aportes o donaciones. El costo incluye gastos de adquisición irreversibles y otros. De decidir su venta y cumplir requisitos, pasa a la cuenta 27. Podría no depreciarse si su vida útil no se ve afectada, salvo deterioro eventual.', 'comments' => 'Se ubica al final del activo no corriente en la presentación. Permite separar bienes de carácter especial sin uso directo en la producción o comercialización. Si surge deterioro, se registra su disminución. Al venderlos, se da de baja, reconociendo ganancia o pérdida en la cuenta de resultados.'],
            ['code' => '39', 'name' => 'DEPREC., AMORTIZACION Y ACUMULADOS', 'content' => 'Contiene la depreciación, amortización o agotamiento acumulados de activos materiales, intangibles y recursos naturales. Refleja el consumo del valor de dichos bienes, reduciendo su importe original o revaluado. Se presenta como cuenta de valuación, restando del activo correspondiente.', 'recognition' => 'Se calcula según métodos que reflejen el patrón de uso (lineal, decreciente, producción, etc.) a lo largo de la vida útil estimada. Si cambian estimaciones de vida útil o método, se ajustan los cargos futuros. Afecta resultados cada periodo. Su reversión puede darse al reevaluar la vida útil.', 'comments' => 'La vida útil se revisa periódicamente. Cuando el activo es revaluado, la amortización se calcula sobre el valor revaluado. Diferencia la depreciación del costo de la revaluación y del costo de financiación capitalizado, si corresponde, mostrando el saldo neto del activo en libros.'],
            ['code' => '40', 'name' => 'TRIBUTOS, CONTRAPRESTACIONES Y APORTES AL S.PENSIO', 'content' => 'Reúne obligaciones por impuestos, contribuciones, retenciones y aportes previsionales, sean propios o de terceros retenidos por la empresa. Incluye el impuesto a las transacciones financieras y saldos tributarios (IGV, renta, etc.) sujetos a compensación o pago ante la administración fiscal.', 'recognition' => 'Se reconocen al valor nominal, deduciendo pagos efectuados o retenciones practicadas, conforme al calendario tributario. Si es de cuenta propia, se registra la obligación; si es retenido a terceros, se refleja la retención. Los saldos pendientes se ajustan según normas o compensaciones.', 'comments' => 'Los tributos con saldo deudor se exponen en el activo si aún no se han aplicado. Las subcuentas ayudan a gestionar pagos a cuenta, saldos por compensar y otros aspectos fiscales. Pueden clasificarse como corrientes o no corrientes. Su detalle se presenta en notas, cumpliendo los requisitos legales vigentes.'],
            ['code' => '41', 'name' => 'REMUNERACIONES Y PARTICIPACIONES POR PAGAR', 'content' => 'Reúne obligaciones con los trabajadores por sueldos, salarios, gratificaciones, participaciones en utilidades y demás beneficios sociales, tanto de corto como de largo plazo. Incluye obligaciones posteriores al retiro, si corresponden, y ajustes de montos pendientes de liquidación.', 'recognition' => 'Se miden al valor nominal, restando cualquier importe ya satisfecho. De existir saldos en moneda extranjera, se convierten al tipo de cambio de la fecha de los estados financieros. Se presenta la porción devengada, pendiente de pago.', 'comments' => 'Si la entidad contrata servicios de independientes, se ubicarán en la cuenta 424. Las participaciones y remuneraciones pendientes no se registran como capital; reflejan el vínculo laboral y la obligación de pago al personal.'],
            ['code' => '42', 'name' => 'CUENTAS POR PAGAR COMERCIALES TERCEROS', 'content' => 'Abarca deudas derivadas de compras de bienes o servicios a proveedores no relacionados, inherentes al giro de la empresa. Engloba facturas, boletas y otros documentos pendientes de pago, con vencimientos y condiciones pactadas.', 'recognition' => 'Se reconocen generalmente a su costo amortizado, que suele coincidir con el valor nominal menos pagos parciales. Para saldos en moneda extranjera, se utiliza el tipo de cambio vigente al cierre del período.', 'comments' => 'Anticipos a proveedores se reclasifican si no corresponden a compras pactadas. Esta cuenta facilita el control de obligaciones comerciales, permitiendo diferenciar los pagos pendientes por transacciones de bienes o servicios.'],
            ['code' => '43', 'name' => 'CUENTAS POR PAGAR COMERCIALES RELACIONADAS', 'content' => 'Comprende las obligaciones comerciales con empresas o entidades vinculadas, por la adquisición de bienes o servicios en el curso normal de actividades. Aplica cuando hay una relación de propiedad o control mutuo entre las partes.', 'recognition' => 'Se mide al costo amortizado, habitualmente igual al valor nominal, descontando pagos efectuados. Si existe un saldo en moneda extranjera, se lo traduce al tipo de cambio de la fecha de presentación de estados financieros.', 'comments' => 'Los saldos deudores pueden clasificarse como activos en la cuenta 432. Permite distinguir las operaciones con partes vinculadas de las transacciones con terceros, brindando transparencia en la información financiera.'],
            ['code' => '44', 'name' => 'CTAS POR PAGAR A LOS ACC.(SOCIOS) Y DIREC.', 'content' => 'Refleja sumas adeudadas por la empresa a sus accionistas, socios, directores y gerentes, distintas de las obligaciones comerciales y laborales habituales. Puede incluir aportes temporales, préstamos y saldos devengados a favor de dichos participantes.', 'recognition' => 'Se reconocen por el importe pendiente de pago, restando abonos efectuados. Los saldos en moneda extranjera se convierten al tipo de cambio de la fecha de cierre. Involucra obligaciones genuinas con personas naturales, no con empresas.', 'comments' => 'Las cuentas de accionistas personas jurídicas se presentan en la cuenta 47. Este rubro identifica deudas con personas vinculadas por su rol directivo o participativo, sin confundirse con operaciones comerciales regulares.'],
            ['code' => '45', 'name' => 'OBLIGACIONES FINANCIERAS', 'content' => 'Contiene préstamos, créditos y emisión de instrumentos de deuda contraídos con entidades financieras u otros prestamistas no relacionados. Incluye costos financieros asociados y cláusulas de derivados vinculados al endeudamiento, si se pactan.', 'recognition' => 'Se reconocen inicialmente al valor razonable, casi siempre al monto recibido neto de costos de transacción, y luego se mide al costo amortizado. Para saldos en moneda extranjera, se aplica el tipo de cambio de la fecha de los estados financieros.', 'comments' => 'Los gastos por intereses pueden capitalizarse si el activo es calificado (NIC 23). Los bienes dados en garantía se controlan en cuentas de orden. Al liquidarse la deuda, se da de baja, reconociendo cualquier diferencia en la cuenta de resultados.'],
            ['code' => '46', 'name' => 'CUENTAS POR PAGAR DIVERSAS TERCEROS', 'content' => 'Agrupa obligaciones con terceros no comerciales ni financieras tradicionales, como deudas tributarias no habituales, descuentos diversos, indemnizaciones, subsidios, u otras transacciones que no constituyen compras de bienes o servicios regulares.', 'recognition' => 'Se miden inicialmente al valor razonable, y luego al costo amortizado si conllevan intereses implícitos. Cuando corresponda a pasivos financieros derivados, se registran a valor razonable. Para moneda extranjera, se usa el tipo de cambio de cierre.', 'comments' => 'Los subsidios de gobierno que exijan condiciones pueden generar un pasivo reembolsable si no se cumplen los requisitos. De cumplirse, se reconocen gradualmente en resultados. Saldos pendientes se modifican conforme a la tasa de interés efectiva.'],
            ['code' => '47', 'name' => 'CUENTAS POR PAGAR DIVERSAS RELACIONADAS', 'content' => 'Reúne deudas con partes vinculadas por transacciones distintas a las comerciales y al financiamiento formal. Pueden ser préstamos, avances, gastos compartidos o reembolsos a empresas del mismo grupo o con participación común.', 'recognition' => 'Se reconocen al valor nominal, ajustado por pagos, reexpresando montos en moneda extranjera al tipo de cambio de cierre. Si devengan intereses, se aplica el método del costo amortizado. Diferencia los pasivos corrientes de los no corrientes.', 'comments' => 'Ayuda a separar obligaciones con partes relacionadas del resto de pasivos. Permite a los usuarios identificar la dependencia financiera interna. Para flujos de efectivo, sirve para mostrar si estos pagos se asocian a inversión, financiamiento u otras operaciones.'],
            ['code' => '48', 'name' => 'PROVISIONES', 'content' => 'Registra obligaciones con alto grado de incertidumbre en monto o vencimiento, derivadas de sucesos pasados que generarían un desembolso probable. Ejemplos: litigios, garantías, desmantelamientos u obligaciones medioambientales.', 'recognition' => 'Se reconocen si existe una obligación presente, es probable la salida de recursos y puede estimarse de forma fiable. Se actualizan al valor presente si el efecto es significativo. Saldos en moneda extranjera se ajustan al tipo de cambio de cierre.', 'comments' => 'Difiere de las cuentas por pagar habituales por la incertidumbre de su importe o plazo. Cambios en estimaciones se reflejan en el periodo en que ocurren. Su reversión procede si se confirma que la obligación no existía o resultó menor.'],
            ['code' => '49', 'name' => 'PASIVO DIFERIDO', 'content' => 'Comprende pasivos que surgen por diferencias temporales gravables (impuestos o participaciones) y por actualizaciones de valor o ingresos no devengados que incrementan la obligación futura, pero no el gasto inmediato. Permite reflejar la base imponible futura.', 'recognition' => 'Se valora al costo, reconociendo la obligación potencial cuando dichas diferencias se revertirán. Incluye la contraparte de partidas que generan un mayor ingreso contable que fiscal. Puede incluir intereses diferidos para separar capital de interés.', 'comments' => 'Subcuentas 491 y 492 conectan con participaciones e impuesto a la renta diferido, respectivamente. Intereses no devengados se compensan con la cuenta por cobrar. Se mantiene hasta la extinción de las diferencias temporales gravables.'],
            ['code' => '50', 'name' => 'CAPITAL', 'content' => 'Refleja los aportes de accionistas, socios o participacionistas legalmente formalizados. Incluye acciones emitidas, en circulación o readquiridas. Engloba el patrimonio nominal que respalda la actividad, sin contemplar sus reservas, utilidades o premios de emisión.', 'recognition' => 'Se reconoce al valor nominal si son aportes en efectivo. En caso de aportes en especie, el capital se registra al valor razonable del bien aportado. Si hay diferencias con el valor pagado, se usan las cuentas de prima o descuento de emisión (cuenta 52).', 'comments' => 'Incluye tanto acciones comunes como preferentes; estas últimas podrían reclasificarse a pasivo si cumplen ciertas condiciones. Los incrementos o reducciones de capital se contabilizan cuando se formalizan legalmente. La suscripción en moneda distinta genera diferencias de emisión.'],
            ['code' => '51', 'name' => 'ACCIONES DE INVERSIÓN', 'content' => 'Agrupa las acciones de inversión formalizadas y las acciones propias readquiridas. Su saldo refleja el monto nominal de dichos títulos y cualquier capitalización efectuada. Permite distinguir aportes patrimoniales distintos de las acciones comunes, registrando la tenencia de terceros u obligación readquirida.', 'recognition' => 'Se registra al valor nominal que representan las acciones, incluido el efecto de las capitalizaciones realizadas. De haber acciones propias readquiridas, su valor nominal se reconoce con la respectiva contrapartida, según se exija legalmente. La medición ulterior depende de disposiciones legales vigentes.', 'comments' => 'Las acciones de inversión pueden diferir en derechos y obligaciones frente a las acciones comunes. Requieren un control de la tenencia efectiva y de la legalización de los aportes. Si se modifican las condiciones, es posible que se reclasifiquen dentro del patrimonio o, en casos particulares, al pasivo.'],
            ['code' => '52', 'name' => 'CAPITAL ADICIONAL', 'content' => 'Reúne primas o descuentos de emisión, aportes en trámite de formalización, o reducciones de capital no concluidas. Refleja incrementos (o decrementos) patrimoniales que aún no se han inscrito legalmente como capital social, manteniéndose de manera transitoria hasta su formalización.', 'recognition' => 'Se contabiliza por el excedente (o déficit) sobre el valor nominal de acciones. Si los aportes están pendientes, se registra al valor que haya sido acordado. Cualquier variación cambiaria al cobrar dichos aportes en moneda extranjera se ajusta directamente en esta cuenta, sin afectar resultados.', 'comments' => 'Es una cuenta transitoria: al completarse la inscripción registral, los importes se transfieren a la cuenta 50. Algunas partidas podrían considerarse pasivos según su sustancia financiera (ej., acciones preferentes con obligaciones de reembolso). Las diferencias de cambio se reconocen en el patrimonio.'],
            ['code' => '56', 'name' => 'RESULTADOS NO REALIZADOS', 'content' => 'Incluye ganancias (o pérdidas) por diferencias de cambio en inversiones en entidades extranjeras, coberturas de flujos de efectivo, e incrementos en valor de activos o pasivos financieros disponibles para la venta. Registra beneficios contables no materializados en efectivo o equivalentes.', 'recognition' => 'Se reconocen conforme se valoran los instrumentos o inversiones subyacentes. Al medirse el activo o pasivo relacionado, las variaciones van aquí en lugar de los resultados corrientes. Se transfieren a ganancias o pérdidas cuando se realiza la operación o se concreta la disposición del instrumento.', 'comments' => 'Las subcuentas 563 y 564 se vinculan con cuentas de activos o pasivos financieros (113 o 464). Sirve para separar las ganancias potenciales de las efectivamente devengadas, manteniendo la transparencia sobre la posición financiera real hasta que esas ganancias se hagan efectivas.'],
            ['code' => '57', 'name' => 'EXCEDENTE DE REVALUACIÓN', 'content' => 'Registra incrementos provenientes de la revaluación de inmuebles, maquinaria, equipo, intangibles o inversiones inmobiliarias. Cubre ajustes a valor de mercado que superan el costo neto, menos amortización y deterioro, reflejando plusvalías no realizadas en la contabilidad.', 'recognition' => 'Tras reconocer el activo al costo, puede optarse por medirlo al valor revaluado según una tasación confiable. El excedente neto de impuesto a la renta y participaciones diferidas se contabiliza aquí. Si se revierte la revaluación, se reduce hasta agotar este excedente y luego afecta resultados.', 'comments' => 'La revaluación no impacta directamente en utilidades del ejercicio, sino que incrementa el patrimonio. Si posteriormente el valor disminuye, primero se afecta este excedente. El impacto final corresponde a la NIC 16 u otras normas especializadas (NIC 38 para intangibles, NIC 40 para inversiones inmobiliarias).'],
            ['code' => '58', 'name' => 'RESERVAS', 'content' => 'Acumula apropiaciones de utilidades formalmente aprobadas por la junta de accionistas (o socios) para fines específicos (reserva legal, estatutaria, u otras). También se incluyen asignaciones destinadas a contingencias, reinversión o cualquier propósito establecido en la normativa.', 'recognition' => 'Se reconocen cuando la empresa decide, o la ley exige, destinar parte de las utilidades acumuladas a reservas. Su valor no vuelve al resultado a menos que dichas reservas se liberen por acuerdo posterior. Reflejan el fortalecimiento patrimonial para contingencias o proyectos futuros.', 'comments' => 'Las reservas se constituyen con utilidades ya devengadas y no representan un gasto. Pueden ser legales (como la reserva legal obligatoria) o voluntarias (por decisión de los socios). Se muestran separadas de los resultados acumulados y se liberan cuando se cumplan las condiciones estatutarias o legales.'],
            ['code' => '59', 'name' => 'RESULTADOS ACUMULADOS', 'content' => 'Refleja utilidades no distribuidas, pendientes de destino, y pérdidas acumuladas de ejercicios anteriores. Es la base para posibles distribuciones a los socios/accionistas o para compensación de pérdidas. También recoge ajustes de ejercicios pasados que impacten directamente en el patrimonio.', 'recognition' => 'Se modifica al cierre de cada ejercicio con la ganancia o pérdida generada, luego de aplicar reservas o destinar utilidades. Si se detectan errores u cambios de políticas contables de períodos anteriores, se ajustan aquí, sin reabrir la contabilidad de ejercicios precedentes.', 'comments' => 'Las decisiones sobre reparto de dividendos o compensación de pérdidas parten del saldo que figura en esta cuenta tras las asignaciones obligatorias a reservas. Representa la historia acumulada de los resultados netos de la entidad, listos para su eventual distribución o el saneamiento patrimonial.'],
            ['code' => '60', 'name' => 'COMPRAS', 'content' => 'Registra las adquisiciones de bienes destinados a la venta, proceso productivo u otros usos inmediatos. Muestra el costo de compra, incluyendo fletes, seguros y gastos asociados. Luego se traspasa al inventario, al gasto o al activo fijo, según la naturaleza y uso final de los bienes.', 'recognition' => 'Se reconoce por el valor de factura y costos adicionales necesarios para poner los bienes en condiciones de uso o venta. Simultáneamente, se transfieren a la cuenta 61 o 72 según su destino (inventario, costo de producción o activo inmovilizado). Se aplican métodos de costeo cuando corresponda.', 'comments' => 'Distingue la compra de mercaderías (subcuenta 601), materias primas (602-604) o insumos varios. Permite valorar correctamente el inventario o el activo receptor del bien. Si se trata de consumo inmediato no capitalizable, se lleva a gasto (vía 791). Apoya la determinación del costo de ventas o de producción.'],
            ['code' => '61', 'name' => 'VARIACIÓN DE INVENTARIOS', 'content' => 'Registra variaciones entre existencias iniciales y finales de mercaderías, materias primas, materiales auxiliares, suministros y envases. Indica si ventas y consumos superan las compras (disminución de inventarios) o si las compras exceden consumos (aumento de inventarios).', 'recognition' => 'Las variaciones se registran como ajuste a las compras en resultados. Un saldo deudor revela menor stock final que inicial, y uno acreedor mayor inventario acumulado. No aplica a productos terminados o en proceso (cuenta 71). Permite mostrar el cambio neto de inventarios en el periodo.', 'comments' => 'Avisa la magnitud de uso o acumulación de inventarios. La variación de envases fabricados se ve en 714. Permite evaluar si el inventario neto se incrementa o reduce, dando transparencia a la contabilidad de existencias y su efecto en resultados.'],
            ['code' => '62', 'name' => 'GASTOS DE PERSONAL Y DIRECTORES', 'content' => 'Agrupa las remuneraciones y beneficios al personal en efectivo o especie, aportes a la seguridad social y dietas a directores. Incluye salarios, bonificaciones, gratificaciones y demás derechos laborales. No engloba servicios de mano de obra tercerizada (que va en cuenta 63).', 'recognition' => 'Se devengan como costo del personal. Se imputan a cuentas de activo o gasto vía la subcuenta 791, según su destino. Aportes a seguridad social y demás beneficios se reconocen del mismo modo, reflejando el gasto laboral en contabilidad.', 'comments' => 'Al tercerizar servicios, se usa la cuenta 63. Remuneraciones extraordinarias se sujetan a la normativa laboral. El registro oportuno permite controlar obligaciones sociales y costos reales de producción o administración.'],
            ['code' => '63', 'name' => 'GASTOS DE SERVICIOS PRESTADOS POR TERCEROS', 'content' => 'Contiene pagos a proveedores externos por servicios recibidos: asesorías, mantenimientos, transportes, comisiones bancarias, etc. No incluye intereses (cuenta 67), seguros particulares (cuenta 65) ni servicios de personal subcontratado (cuenta 62).', 'recognition' => 'Se devengan al recibir el servicio. Si están relacionados con la compra o producción de activos inmovilizados, se transfieren a 72. Gastos bancarios se reúnen en 6391, los intereses se van a 67. Esto asigna correctamente cada servicio al rubro correspondiente.', 'comments' => 'La separación entre servicios generales y otros gastos evita confusiones. Servicios que incrementan activos (ej. maquinaria) se capitalizan. Seguros de vida o salud se registran en 627, o se incluyen al costo de inventarios si corresponden. Este control garantiza transparencia en la gestión.'],
            ['code' => '64', 'name' => 'GASTOS POR TRIBUTOS', 'content' => 'Recoge impuestos, tasas y contribuciones a cargo de la empresa, excepto el Impuesto a la Renta (cuenta 88), y multas e intereses relacionados (cuentas 65 y 67). Incluye el IGV no deducible y otros tributos indirectos irreembolsables.', 'recognition' => 'Se devengan al surgir la obligación tributaria. El IGV no acreditable se registra como gasto. El Impuesto a la Renta va a 88. Intereses tributarios se llevan a 6737 y multas a 6592, distinguiendo cada naturaleza. Esto clarifica el reconocimiento contable de las distintas cargas impositivas.', 'comments' => 'Tributos no atribuibles a un activo específico se registran aquí. Si inciden en activos (p.ej. importaciones), se capitalizan. Esto distingue el costo fiscal real de la operación y brinda claridad en la presentación de gastos ante la administración tributaria.'],
            ['code' => '65', 'name' => 'OTROS GASTOS DE GESTIÓN', 'content' => 'Acumula gastos generales no clasificados como consumo de bienes productivos, remuneraciones, tributos, intereses ni depreciaciones. Incluye costos administrativos, seguros no asignables directamente a producción, gastos de oficina y similares.', 'recognition' => 'Se devengan cuando se incurren en gastos no vinculados a la producción o servicios. Pueden derivar de operaciones discontinuadas o gastos no capitalizables. Si corresponde a insumos, va a 603 (materiales auxiliares) o 609 (costos vinculados).', 'comments' => 'Los seguros de vida y salud del personal van a 627. Otros seguros o gastos deben analizarse para su registro correcto. Las compras de útiles de oficina suelen ir en 603. La distinción contable evita mezclar gastos operativos con costos productivos.'],
            ['code' => '66', 'name' => 'PÉRDIDA POR MEDICIÓN DE ACTIVOS NO FINANCIEROS', 'content' => 'Registra la disminución del valor razonable de activos no financieros (propiedades, equipos, inventarios, biológicos, intangibles), cuando su precio de mercado o tasación es menor que su importe en libros, generando una pérdida contable.', 'recognition' => 'Sucede al medir o revalorar dichos activos y comprobar un valor actual menor al registrado. No aplica a activos financieros (estos van a 677). Refleja oportunamente la merma en activos no financieros valorados a fair value.', 'comments' => 'Esta pérdida difiere del deterioro (cuenta 68) en activos medidos al costo. Aplica a mediciones a fair value (NIC 16, NIC 40, NIC 41, etc.). Su reversión depende de normas específicas, si el valor se recupera. Las pérdidas en activos financieros van a 677.'],
            ['code' => '67', 'name' => 'GASTOS FINANCIEROS', 'content' => 'Incluye intereses y cargos financieros por préstamos, líneas de crédito, diferenciales cambiarios negativos y pérdidas por valuación a fair value de pasivos o instrumentos financieros. No incluye intereses capitalizables (NIC 23), que se añaden al costo de activos calificados.', 'recognition' => 'Se devengan en el periodo en que se incurren. Los intereses capitalizables se registran en activos hasta que estén listos para su uso. La subcuenta 6792 agrupa costos de actualización por medición a valor descontado, ajustando los gastos financieros globales.', 'comments' => 'Las pérdidas por medición de activos financieros se reflejan en 677. Los gastos bancarios por comisiones y servicios se registran en 6391, salvo que sean interés. Separar los costos de financiamiento facilita el análisis de la estructura financiera y la rentabilidad.'],
            ['code' => '68', 'name' => 'VALUACIÓN Y DETERIORO DE ACTIVOS Y PROVISIONES', 'content' => 'Agrupa cargos por depreciación, amortización, agotamiento, deterioro de valor de activos al costo, provisiones de litigios o desmantelamiento, y ajustes similares. Permite reflejar la reducción del valor contable de activos o la constitución de pasivos estimados.', 'recognition' => 'Se devengan al transcurrir la vida útil o ante indicios de deterioro. Provisiones se constituyen por obligaciones probables e importe incierto. Si el tiempo influye, se descuenta a valor presente y la parte financiera se registra en 6792. Refleja la pérdida de valor o la creación de obligaciones de forma adecuada.', 'comments' => 'Se vincula con las subcuentas 391, 392, 393, la 36 y la 48. La reversión de deterioro se registra en 757. Estos cargos se pueden asignar a producción o gasto a través de la cuenta 78. Distinguirlos mejora la claridad de los estados financieros y la medición de resultados.'],
            ['code' => '69', 'name' => 'COSTO DE VENTAS', 'content' => 'Registra el costo de bienes o servicios enajenados en el giro del negocio. Para mercaderías, se aplica un método de costeo (PEPS, promedio, etc.). Para servicios, agrupa costos incurridos en la prestación. Su saldo refleja lo que costó producir o adquirir lo vendido.', 'recognition' => 'Se transfiere a resultados cuando se efectúa la venta. Se vincula con la cuenta 60 y 61, 71 o 72 según el tipo de bien o servicio. El costo efectivo surge tras aplicar métodos de costeo y ajustes de inventarios, relacionándolo con 611 u otras subcuentas, reflejando la salida al vender.', 'comments' => 'Es esencial para determinar la rentabilidad bruta. Un control adecuado de inventarios y costos es vital para la exactitud de los estados financieros. La transferencia de saldos de producción a costo de ventas se refleja en subcuentas específicas, evitando confusión con gastos de operación.'],
            ['code' => '70', 'name' => 'VENTAS', 'content' => 'Acumula ingresos por ventas de bienes o servicios propios del negocio, diferenciando ventas a terceros y a entidades relacionadas. Aplica cuando hay transferencia de riesgos y beneficios, probabilidad de cobro y medición confiable del ingreso y costos incurridos.', 'recognition' => 'Surge al traspasar control y riesgos al comprador, con probabilidad de cobro y medición fiable. Para servicios, se requiere medir el avance. Descuentos por pronto pago van a 675; intereses a 772. Se lleva a resultados en el periodo que ocurre la transacción.', 'comments' => 'Revela la principal fuente de ingresos en negocios de bienes o servicios. Aplica lineamientos IFRS: medición fiable, transferencia de riesgos y probabilidad de cobro. Un control claro refleja la facturación real y la utilidad del periodo, distinguiendo descuentos e intereses.'],
            ['code' => '71', 'name' => 'VARIACIÓN DE LA PRODUCCIÓN ALMACENADA', 'content' => 'Refleja el cambio entre inventarios iniciales y finales de productos en proceso, productos terminados, subproductos, desechos, envases y embalajes elaborados, y servicios en proceso. Un saldo deudor indica que se vendió más de lo producido (se usó inventario inicial); uno acreedor indica lo contrario.', 'recognition' => 'Ajusta los resultados como cuenta correctora de los ingresos. Saldo deudor: la venta supera la producción y se reduce inventario. Saldo acreedor: la producción supera la venta, incrementando inventario. Los cambios en mercaderías compradas van en la cuenta 61, no aquí.', 'comments' => 'La variación de productos terminados y en proceso contribuye a mostrar la diferencia entre producción y ventas. Envases y embalajes fabricados se registran aquí, mientras los comprados van en 61. Expresa cómo los movimientos de inventarios impactan el resultado por la vía de la producción almacenada.'],
            ['code' => '72', 'name' => 'PRODUCCIÓN DE ACTIVO INMOVILIZADO', 'content' => 'Recoge el costo incurrido al construir o fabricar activos inmovilizados para alquiler, venta posterior o uso interno. Transfiere los costos acumulados (del Elemento 6) a la cuenta de activo respectiva. Si existen costos financieros capitalizables, se canalizan por su subcuenta (p.ej. 725) sin afectar la producción.', 'recognition' => 'La capitalización de costos se efectúa conforme a NIC 23 (costos financieros), NIC 16, NIC 38 o NIC 40, según aplique. Al concluir la obra o fabricación, el monto se reclasifica desde cuentas de costos y gastos (Elemento 6) hacia el activo inmovilizado, reflejando el incremento patrimonial por construcción propia.', 'comments' => 'Muestra ingresos en la contabilidad de explotación, pero en la financiera se neutraliza al activar el costo. Sirve para reconocer inversiones hechas por la propia empresa. Las transferencias involucran la cuenta 81 para gastos operativos o la 85 para resultados antes de participaciones, según la naturaleza de los costos capitalizados.'],
            ['code' => '73', 'name' => 'DESCUENTOS, REBAJAS Y BONIFICACIONES OBTENIDOS', 'content' => 'Acumula deducciones monetarias recibidas tras compras de bienes y servicios. Incluye descuentos por volumen, rebajas posteriores, bonificaciones y reducciones similares, distintas del pronto pago. Si el activo ya está en uso, se disminuye su valor y se ajustan las depreciaciones futuras.', 'recognition' => 'Se reconocen cuando la entidad obtiene la rebaja tras haber facturado los bienes o servicios. Si todavía no se incorporó el bien a la contabilidad, se descuenta del costo de adquisición; si el bien ya está capitalizado o se consumió, se refleja como un ingreso o reducción de valor, según lo que indiquen las NIIF.', 'comments' => 'Los descuentos por pronto pago van a la subcuenta 775. Las NIIF exigen reducir el costo del activo si es parte de su precio original; si se otorga tras su incorporación, también se corrige el valor del activo y la amortización futura. Esto evita inflar gastos o activos.'],
            ['code' => '74', 'name' => 'DESCUENTOS, REBAJAS Y BONIFICACIONES CONCEDIDOS', 'content' => 'Registra las deducciones monetarias y bonificaciones que la empresa otorga a sus clientes, distintas de los descuentos por pronto pago. Estas reducciones ajustan el importe bruto de las ventas facturadas, mostrando el valor final efectivamente cobrado al cliente.', 'recognition' => 'Se contabilizan al concederse la reducción posterior a la venta. Disminuyen los ingresos de la operación al reflejar un menor ingreso neto por la transacción. Los descuentos por pronto pago son gastos financieros en la subcuenta 675, no se registran aquí.', 'comments' => 'Afectan el resultado operativo, corrigiendo la facturación inicial. Sirven para separar las concesiones por rebajas comerciales de los costes financieros asociados a pronto pago. Facilita la presentación clara de la política de descuentos y su impacto en los estados financieros.'],
            ['code' => '75', 'name' => 'OTROS INGRESOS DE GESTIÓN', 'content' => 'Incluye los ingresos incidentales ajenos a la actividad principal, como comisiones, corretajes, regalías, alquileres, o indemnizaciones. Excluye ingresos financieros (77) y ventas propias del giro. Se reflejan como un componente distinto de los ingresos de explotación.', 'recognition' => 'Se reconocen al devengarse en operaciones secundarias del negocio. Si implican la cesión de activos productivos, se consideran ingresos operativos solo si el giro principal lo permite. De lo contrario, se clasifican como ingresos accesorios. Pueden transferirse a la 77 si son intereses u otros rendimientos financieros.', 'comments' => 'Ayuda a diferenciar ingresos no relacionados directamente con la producción o venta principal de la entidad, manteniendo la transparencia. Si se deviene habitual y encaja con el giro, puede clasificarse como parte de la actividad principal. Esto puede influir en la presentación final de las cuentas de resultados.'],
            ['code' => '76', 'name' => 'GAN. POR MEDICIÓN DE ACT. NO FINANCIEROS AL VALOR RA', 'content' => 'Reconoce aumentos de valor razonable en activos no financieros (inmuebles, biológicos, intangibles, etc.), comparando su valor de mercado con su importe en libros. No se aplica a instrumentos financieros, cuyos ajustes se registran en la cuenta 77. Revela la mejora contable del activo sin venta efectiva.', 'recognition' => 'Se da cuando se aplica medición a fair value según NIC 16, NIC 40 o NIC 41, generando un incremento con contrapartida en resultados. Puede revertirse si el valor baja posteriormente o si, según las NIIF, corresponde reclasificarlo a revalorizaciones (57) o patrimonio. Refleja un beneficio sin realización inmediata.', 'comments' => 'Es distinta de la revaluación de costo. Si las normas exigen presentar el incremento como revaluación (ej., modelo de revaluación de NIC 16), va a la cuenta 57. Si es una medición de fair value por políticas contables, se registra aquí. Permite distinguir incrementos por valorización de activos no financieros de otros resultados no operativos.'],
            ['code' => '77', 'name' => 'INGRESOS FINANCIEROS', 'content' => 'Reúne intereses, dividendos, diferencias de cambio favorables, descuentos por pronto pago obtenidos y ganancias por medición de activos y pasivos financieros a valor razonable. Representa el rendimiento económico o ventajas financieras derivadas de colocación o tenencia de capital.', 'recognition' => 'Se devengan conforme a los convenios (intereses) o actos (dividendos declarados), o a la fecha de medición de instrumentos financieros. Si incluye un componente de valor descontado (7792), registra el reconocimiento de ingresos a medida que pasa el tiempo o se cumple la condición financiera.', 'comments' => 'La subcuenta 773 contempla dividendos si las utilidades corresponden a periodos posteriores a la adquisición de la inversión. Si fueron generadas antes, se reduce el valor de la inversión. También recoge los efectos positivos de las variaciones cambiarias y descuentos por pronto pago. Es clave para analizar la posición financiera global más allá del negocio principal.'],
            ['code' => '78', 'name' => 'CARGAS CUBIERTAS POR PROVISIONES', 'content' => 'Permite reexpresar los gastos del ejercicio que se compensan con provisiones registradas en la cuenta 68 en períodos anteriores. Muestra la utilización efectiva de dichas provisiones, reduciendo la obligación asumida y sin generar ingresos netos, pues solo revierte un gasto ya estimado.', 'recognition' => 'Se activa cuando una provisión reconocida se consume al ocurrir el hecho que la originó (ej. pago de indemnización). El gasto real se registra en la cuenta 6, pero se compensa con esta cuenta, anulando la doble imputación. No genera ingresos, solo refleja la aplicación de la provisión.', 'comments' => 'Distingue la diferencia entre gasto nuevo y gasto previsto. Sirve para transparentar el uso de provisiones constituidas. Evita duplicar el gasto, limitándolo a la porción no cubierta. Las provisiones relacionadas con activos construidos por la empresa se transfieren a la cuenta 72. Permite un control acertado de salidas efectivas vs. estimaciones anteriores.'],
            ['code' => '79', 'name' => 'CARGAS IMPUTABLES A CUENTAS DE COSTOS Y GASTOS', 'content' => 'Sirve de nexo para asignar gastos por naturaleza (del Elemento 6) a las cuentas de costos y gastos (Elemento 9) en la contabilidad analítica de explotación. No genera ingresos; compensa los cargos con abono en costos o gastos, reflejando la función real de cada desembolso.', 'recognition' => 'A final de periodo, su saldo acreedor debe coincidir con los débitos en las cuentas de costos y gastos que recibe. Los gastos previstos (ej. provisiones) se mueven por la cuenta 78. Los gastos implicados en producción de activos se llevan a la 72, diferenciando así costes directos del negocio, gastos y capitalizaciones.', 'comments' => 'Separa la contabilidad por naturaleza (Elemento 6) de la funcional (Elemento 9), esencial en contabilidad de costos. Permite asignar con precisión a la fabricación, comercialización o administración, facilitando el análisis de rentabilidad. La cuenta no se presenta como ingreso, es simplemente un medio de transferencia contable.'],
            ['code' => '80', 'name' => 'MARGEN COMERCIAL', 'content' => 'Mide la diferencia entre ventas de mercaderías y su costo de venta. Refleja la ganancia bruta de comercialización cuando no hay proceso de transformación significativo. La determinación del costo combina compras, variación de inventarios, descuentos por pronto pago (gasto financiero), etc.', 'recognition' => 'Se calcula tras cerrar las cuentas de ventas y de costo de ventas, mostrando la utilidad bruta en operaciones de compra-venta. Permite evaluar la eficiencia comercial del periodo, separando el impacto del costo de mercaderías de otros costos o gastos operativos.', 'comments' => 'El margen comercial es base para medir la rentabilidad de negocios dedicados a la reventa. No incluye gastos financieros de pronto pago, que se registran en la cuenta 67, ni gastos de personal, administración u otros costos no directamente ligados al costo de la mercadería. Lo complementa el cálculo de resultados netos tras sumar o restar otros rubros del estado de resultados.'],
            ['code' => '81', 'name' => 'PRODUCCIÓN DEL EJERCICIO', 'content' => 'Refleja el valor total producido por la empresa durante el período, ya sea vendido, almacenado o capitalizado en activos propios (bienes, servicios o inmovilizados). Incluye la consideración de existencias de servicios y la autoconstrucción de activos, acorde con las normas NIIF.', 'recognition' => 'Se determina al contabilizar las salidas e ingresos de inventarios de productos terminados, servicios elaborados y activos fabricados. En la contabilidad analítica puede verse como un ingreso que compensa el costo, aun cuando no exista venta inmediata, reflejando la generación de valor.', 'comments' => 'Las NIIF consideran que los servicios en proceso también pueden mantenerse como existencias. La producción de activos inmovilizados se separa en cuentas específicas para evidenciar qué parte de la producción pasa a capitalizarse. Integra el monto global que la empresa ha generado en el ejercicio, aun sin venta.'],
            ['code' => '82', 'name' => 'VALOR AGREGADO', 'content' => 'Representa la diferencia entre la producción del período y los consumos intermedios adquiridos a terceros. Equivale a la suma de las remuneraciones pagadas al trabajo y al capital, señalando la creación de riqueza de la empresa para la economía. Refleja el aporte económico neto de la actividad.', 'recognition' => 'Se obtiene restando a la producción todos los bienes y servicios externos consumidos en el proceso. No figura como línea independiente en el estado de resultados, pero aparece antes del resultado de explotación. Permite medir la contribución de la empresa al PBI y su eficiencia en la transformación de recursos.', 'comments' => 'El valor agregado mide la capacidad de una entidad para generar riqueza a partir de insumos adquiridos externamente. Su análisis sirve para evaluar la eficiencia productiva y la aportación macroeconómica. También coincide con el total de retribuciones pagadas a la mano de obra (salarios) y al capital (ganancias o intereses).'],
            ['code' => '83', 'name' => 'EXCEDENTE BRUTO (INSUFICIENCIA BRUTA) DE EXPLOTACIÓN', 'content' => 'Mide el resultado económico básico tras cubrir consumos intermedios. Si existe excedente, la explotación genera fondos; si es insuficiente, agota recursos previos. Enfatiza la productividad real de la actividad, sin aún considerar gastos de personal ni subsidios como partidas externas.', 'recognition' => 'Parte del valor agregado y se ajusta con las remuneraciones al personal, tributos y eventuales subsidios. Si dichos costos superan el valor generado, surge insuficiencia. Si no, se obtiene excedente bruto. Va previo al resultado operativo, reflejando la fuerza productiva de la empresa en términos económicos.', 'comments' => 'En la óptica contable, los gastos de personal y tributos suelen verse dentro del resultado operativo. Sin embargo, este indicador examina la rentabilidad primaria antes de dichas erogaciones. Los subsidios que compensan costos se incluyen para mostrar si la actividad sería viable sin ayudas externas.'],
            ['code' => '84', 'name' => 'RESULTADO DE EXPLOTACIÓN', 'content' => 'Expresa la utilidad de las operaciones principales de la empresa, sin incluir costos financieros, participaciones ni impuestos. Refleja la rentabilidad estricta de la explotación, antes de partidas extraordinarias o ajenas al giro principal.', 'recognition' => 'Se determina tras deducir costos operativos vinculados a la producción y venta, diferenciando lo que no corresponde a la financiación ni a impuestos. Usualmente coincide con el resultado antes de intereses, participaciones y tributos en estados de resultados por función.', 'comments' => 'Esta cifra permite evaluar la eficiencia económica de la actividad central de la empresa. Es un referente para inversores y administradores, pues excluye factores como deuda o fiscalidad, centrándose solo en la capacidad de generar beneficios en el núcleo del negocio.'],
            ['code' => '85', 'name' => 'RESULTADO ANTES DE PARTICIPACIONES E IMPUESTOS', 'content' => 'Muestra el resultado global tras sumar o restar ingresos y gastos no operativos a la explotación, pero todavía sin aplicar las participaciones de trabajadores ni el impuesto a la renta. Es la base a la que se les calcularán dichas deducciones.', 'recognition' => 'Se obtiene añadiendo o restando al resultado de explotación los gastos e ingresos de naturaleza financiera o extraordinaria. Queda pendiente deducir las participaciones y el impuesto a la renta. Provee una vista del beneficio o pérdida antes de obligaciones con personal y fisco.', 'comments' => 'Facilita separar la parte que corresponde a trabajadores y al Estado de la que pertenece a los accionistas. Suele llamarse EBIT en análisis financiero (Earnings Before Interest and Taxes), sumando aquí también los efectos extraordinarios antes de tributos, según el método contable de presentación.'],
            ['code' => '88', 'name' => 'IMPUESTO A LA RENTA', 'content' => 'Registra el impuesto corriente sobre la renta del ejercicio y la porción diferida derivada de diferencias temporales entre bases contables y tributarias. Incluye, además, la compensación de pérdidas tributarias si es probable que existan utilidades futuras para absorberlas.', 'recognition' => 'Se reconoce a valor nominal, aplicando la legislación fiscal vigente. El impuesto corriente se calcula sobre la renta imponible del periodo. El diferido considera la reversión de diferencias temporales, generando pago futuro o recuperación. También registra ahorros por pérdidas arrastrables si se estima probable su compensación.', 'comments' => 'Las diferencias temporales pueden dar lugar a pasivos o activos por impuesto a la renta diferido. Si se cumplen las condiciones, se activa el beneficio fiscal de pérdidas pasadas. Contribuye a la presentación fiel de la carga tributaria efectiva que pesa sobre la empresa y su proyección futura.'],
            ['code' => '89', 'name' => 'DETERMINACIÓN DEL RESULTADO DEL EJERCICIO', 'content' => 'Muestra la utilidad o pérdida final del período tras incorporar todos los ingresos, costos, gastos, participaciones y el efecto del impuesto a la renta (corriente y diferido). Culmina el estado de resultados y se transfiere a los resultados acumulados en el patrimonio.', 'recognition' => 'Surge al cierre contable, sumando el resultado antes de participaciones e impuestos con las deducciones y adiciones finales correspondientes. Refleja la ganancia o pérdida neta definitiva, pendiente de destino (dividendos, reservas, compensación de pérdidas anteriores, etc.).', 'comments' => 'Esta cuenta cierra el ciclo de la actividad económica del periodo. Su saldo se traspasa a resultados acumulados (cuenta 59), listos para eventuales distribuciones o la cobertura de pérdidas. Permite evaluar la rentabilidad neta luego de todas las erogaciones y cargas fiscales.']

        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        DB::table('ledger_account_recognitions')->delete();
    }
}
