<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

//2024_12_30_000007_insert_subdiaries

class InsertSubdiaries extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::table('sub_diaries')->insert([
            [
                'code' => '00',
                'date' => '2025-01-01',
                'description' => 'APERTURA',
                'book_code' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '01',
                'date' => '2025-01-01',
                'description' => 'COBROS - PAGOS',
                'book_code' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '05',
                'date' => '2025-01-01',
                'description' => 'VENTAS',
                'book_code' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '09',
                'date' => '2025-01-01',
                'description' => 'LETRAS POR COBRAR',
                'book_code' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'code' => '11',
                'date' => '2025-01-01',
                'description' => 'COMPRAS DEL MES',
                'book_code' => '8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '15',
                'date' => '2025-01-01',
                'description' => 'RECIBO POR HONORARIOS',
                'book_code' => '8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '25',
                'date' => '2025-01-01',
                'description' => 'LETRAS POR PAGAR',
                'book_code' => '8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => '35',
                'date' => '2025-01-01',
                'description' => 'PLANILLA DE SUELDOS',
                'book_code' => '31',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);

        DB::table('sub_diary_items')->insert([
            [
                'sub_diary_code' => '00',
                'code' => '101101',
                'description' => 'CAJA M.N',
                'general_description' => 'Asiento de apertura',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '00-000001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '00',
                'code' => '104101',
                'description' => 'BANCO DE CREDITO',
                'general_description' => 'Asiento de apertura',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '00-000002',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '00',
                'code' => '121201',
                'description' => 'FACTURAS POR COBRAR EMITIDAS CARTERA TERCEROS M.N.',
                'general_description' => 'Asiento de apertura',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '00-000003',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '00',
                'code' => '201111',
                'description' => 'MERCADERIAS - COSTO',
                'general_description' => 'Asiento de apertura',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '00-000004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '00',
                'code' => '331111',
                'description' => 'TERRENOS-COSTO',
                'general_description' => 'Asiento de apertura',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '00-000005',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '00',
                'code' => '333111',
                'description' => 'MAQUINARIAS Y EQUIPOS DE EXPLOTACION-COSTO',
                'general_description' => 'Asiento de apertura',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '00-000006',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '00',
                'code' => '401711',
                'description' => 'RENTA DE TERCERA CATEGORIA',
                'general_description' => 'Asiento de apertura',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '00-000007',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '00',
                'code' => '421201',
                'description' => 'FACTURAS EMITIDAS POR PAGAR M.N. TERCEROS',
                'general_description' => 'Asiento de apertura',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '00-000008',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '00',
                'code' => '451101',
                'description' => 'INSTITUCIONES FINANCIERAS M.N.',
                'general_description' => 'Asiento de apertura',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '00-000009',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '00',
                'code' => '501101',
                'description' => 'ACCIONES',
                'general_description' => 'Asiento de apertura',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '00-000010',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '00',
                'code' => '591101',
                'description' => 'UTILIDADES ACUMULADAS',
                'general_description' => 'Asiento de apertura',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '00-000011',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'sub_diary_code' => '01',
                'code' => '101101',
                'description' => 'CAJA M.N.',
                'general_description' => 'Cobro a clientes',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '01',
                'code' => '121201',
                'description' => 'FACTURAS POR COBRAR EMITIDAS CARTERA TERCEROS M.N.',
                'general_description' => 'Cobro a clientes',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000002',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '01',
                'code' => '421201',
                'description' => 'FACTURAS EMITIDAS POR PAGAR M.N. TERCEROS',
                'general_description' => 'Pago a proveedores',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000003',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '01',
                'code' => '104101',
                'description' => 'BANCO DE CREDITO',
                'general_description' => 'Pago a proveedores',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '01',
                'code' => '411101',
                'description' => 'SUELDOS',
                'general_description' => 'Pago a trabajadores',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000005',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '01',
                'code' => '104101',
                'description' => 'BANCO DE CREDITO',
                'general_description' => 'Pago a trabajadores',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000006',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '01',
                'code' => '424101',
                'description' => 'HONORARIOS POR PAGAR M.N.',
                'general_description' => 'Pago de recibos por honorarios',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000007',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '01',
                'code' => '104101',
                'description' => 'BANCO DE CREDITO',
                'general_description' => 'Pago de recibos por honorarios',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000008',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '01',
                'code' => '639101',
                'description' => 'GASTOS BANCARIOS',
                'general_description' => 'Pago de gastos diversos',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000009',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '01',
                'code' => '104101',
                'description' => 'BANCO DE CREDITO',
                'general_description' => 'Pago de gastos diversos',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000010',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '01',
                'code' => '401111',
                'description' => 'IGV - CUENTA PROPIA',
                'general_description' => 'Pago de impuestos',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000011',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '01',
                'code' => '401711',
                'description' => 'RENTA DE TERCERA CATEGORIA',
                'general_description' => 'Pago de impuestos',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000012',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '01',
                'code' => '104101',
                'description' => 'BANCO DE CREDITO',
                'general_description' => 'Pago de impuestos',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000013',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '01',
                'code' => '401731',
                'description' => 'RENTA DE QUINTA CATEGORIA',
                'general_description' => 'Pago de planilla',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000014',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '01',
                'code' => '417101',
                'description' => 'ADMINISTRADORAS DE FONDOS DE PENSIONES',
                'general_description' => 'Pago de planilla',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000015',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '01',
                'code' => '403101',
                'description' => 'ESSALUD',
                'general_description' => 'Pago de planilla',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000016',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '01',
                'code' => '403201',
                'description' => 'ONP',
                'general_description' => 'Pago de planilla',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000017',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '01',
                'code' => '104101',
                'description' => 'BANCO DE CREDITO',
                'general_description' => 'Pago de planilla',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '01-000018',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'sub_diary_code' => '05',
                'code' => '121201',
                'description' => 'FACTURAS POR COBRAR EMITIDAS CARTERA TERCEROS',
                'general_description' => 'Ventas del mes',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '05-000001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '05',
                'code' => '701211',
                'description' => 'MERCADERIAS VENTA LOCAL TERCEROS',
                'general_description' => 'Ventas del mes',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '05-000002',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '05',
                'code' => '401111',
                'description' => 'IGV - CUENTA PROPIA',
                'general_description' => 'Ventas del mes',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '05-000003',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '09',
                'code' => '123201',
                'description' => 'LETRAS POR COBRAR EN CARTERA TERCEROS M.N.',
                'general_description' => 'Letras por cobrar',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '09-000001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '09',
                'code' => '121201',
                'description' => 'FACTURAS POR COBRAR EMITIDAS CARTERA TERCEROS M.N.',
                'general_description' => 'Letras por cobrar',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '09-000002',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '11',
                'code' => '601101',
                'description' => 'MERCADERIAS',
                'general_description' => 'Compras del mes',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '11-000001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '11',
                'code' => '401111',
                'description' => 'IGV - CUENTA PROPIA',
                'general_description' => 'Compras del mes',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '11-000002',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '11',
                'code' => '421201',
                'description' => 'FACTURAS EMITIDAS POR PAGAR M.N. TERCEROS',
                'general_description' => 'Compras del mes',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '11-000003',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Recibo por honorarios
            [
                'sub_diary_code' => '15',
                'code' => '632101',
                'description' => 'ADMINISTRATIVA',
                'general_description' => 'Recibo por honorarios',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '13-000001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '15',
                'code' => '401721',
                'description' => 'RENTA DE CUARTA CATEGORIA',
                'general_description' => 'Recibo por honorarios',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '13-000002',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '15',
                'code' => '424101',
                'description' => 'HONORARIOS POR PAGAR M.N.',
                'general_description' => 'Recibo por honorarios',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '13-000003',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Letras por pagar
            [
                'sub_diary_code' => '25',
                
                'code' => '423101',
                'description' => 'LETRAS POR PAGAR M.N. TERCEROS',
                'general_description' => 'Letras por pagar',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '14-000001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '25',
                'code' => '421201',
                'description' => 'FACTURAS EMITIDAS POR PAGAR M.N. TERCEROS',
                'general_description' => 'Letras por pagar',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '14-000002',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Planilla de sueldos
            [
                'sub_diary_code' => '35',
                'code' => '621101',
                'description' => 'SUELDOS',
                'general_description' => 'Planilla de sueldos',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '31-000001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '35',
                'code' => '627101',
                'description' => 'REGIMEN DE PRESTACIONES DE SALUD',
                'general_description' => 'Planilla de sueldos',
                'debit' => 1,
                'credit' => 0,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '31-000002',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '35',
                'code' => '411101',
                'description' => 'SUELDOS',
                'general_description' => 'Planilla de sueldos',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '31-000003',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '35',
                'code' => '401731',
                'description' => 'RENTA DE QUINTA CATEGORIA',
                'general_description' => 'Planilla de sueldos',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '31-000004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '35',
                'code' => '403201',
                'description' => 'ONP',
                'general_description' => 'Planilla de sueldos',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '31-000005',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '35',
                'code' => '417101',
                'description' => 'ADMINISTRADORAS DE FONDOS DE PENSIONES',
                'general_description' => 'Planilla de sueldos',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '31-000006',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sub_diary_code' => '35',
                'code' => '403101',
                'description' => 'ESSALUD',
                'general_description' => 'Planilla de sueldos',
                'debit' => 0,
                'credit' => 1,
                'debit_amount' => 0,
                'credit_amount' => 0,
                'correlative_number' => '31-000007',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);


    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        DB::table('sub_diary_items')->truncate();
        DB::table('sub_diaries')->truncate();
    }
}