# Flujo de trabajo de bienvenida para nuevos contribuidores
# Versi贸n simplificada para principiantes

name: Bienvenida a Contribuidores

# Eventos que activan el workflow
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  # Job de bienvenida
  welcome:
    name: Dar la bienvenida a nuevos contribuidores
    runs-on: ubuntu-latest
    
    steps:
    # Verificar si es el primer contribution
    - name: Verificar primer contribution
      uses: actions/github-script@v6
      id: check-contributor
      with:
        script: |
          const { data: issues } = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            creator: context.payload.sender.login,
            state: 'all'
          });
          
          const isFirstContribution = issues.length <= 1;
          return isFirstContribution;
    
    # Dar la bienvenida si es primer contribution
    - name: Bienvenida a nuevos contribuidores
      if: steps.check-contributor.outputs.result == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          const message = `
           **隆Bienvenido/a a Stack Facturador Smart!** 
          
          隆Gracias por tu primera contribution a este proyecto! 叼
          
          ###  Recursos 煤tiles:
          - [Gu铆a de Contribuci贸n](.github/CONTRIBUTING.md)
          - [Documentaci贸n del Proyecto](README.md)
          - [Configuraci贸n de GitHub Actions](.github/workflows/README.md)
          
          ###  Pr贸ximos pasos:
          1. Lee nuestra gu铆a de contribuci贸n
          2. Configura tu ambiente de desarrollo
          3. Busca issues con la etiqueta \`good first issue\`
          4. 隆Sigue contribuyendo!
          
          ###  驴Necesitas ayuda?
          - Revisa nuestra documentaci贸n
          - Crea un issue si tienes preguntas
          - Contacta al equipo: devops@solucionessystem.com
          
          隆Estamos emocionados de tenerte en la comunidad! 
          `;
          
          if (context.payload.issue) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: message
            });
          } else if (context.payload.pull_request) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: message
            });
          }
    
    # Agregar etiqueta de primer contribution
    - name: Etiquetar primer contribution
      if: steps.check-contributor.outputs.result == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          if (context.payload.issue) {
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              labels: ['first-contribution']
            });
          } else if (context.payload.pull_request) {
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['first-contribution']
            });
          }